In [38]:
pip install geopy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: geopy in c:\users\arthu\appdata\roaming\python\python313\site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in c:\users\arthu\appdata\roaming\python\python313\site-packages (from geopy) (2.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [40]:
df_burn = pd.read_excel("../data/NIRD 20230130 Database_Hackathon.xlsx", sheet_name="Data Table NIRD 20230130")

## Final Task

### Subtask:
Provide a summary of the analysis, including the count of non-burn centers identified beyond the 150-mile range, and display the interactive Folium map.

## Summary:

### Q&A
*   How many non-burn centers were identified beyond the 150-mile range of a burn center?
    *   A total of 457 non-burn centers were identified where the closest burn center was more than 150 miles away.
*   Was the interactive Folium map displayed?
    *   Yes, an interactive Folium map was successfully generated and displayed, visualizing both burn centers and the identified non-burn centers beyond the 150-mile range.

### Data Analysis Key Findings
*   The process successfully identified 457 non-burn centers where their closest burn center was at a distance greater than 150 miles.
*   An interactive Folium map was created to visualize these locations, clearly distinguishing burn centers (red markers with a 20-mile red radius circle) from the identified non-burn centers (blue markers).

### Insights or Next Steps
*   The significant number of non-burn centers beyond 150 miles from a burn center highlights areas where access to specialized burn care is most limited. These regions may heavily rely on telemedicine for initial consultation and management.
*   This distance range strongly suggests that air transportation would be necessary for patient transfer, if physical transfer is required. Emphasis should be placed on establishing robust aeromedical transport protocols and infrastructure.
*   Further analysis could focus on evaluating the feasibility and necessity of establishing new burn centers or specialized burn units in these underserved areas to reduce critical travel times and improve patient outcomes.

In [41]:
df_burn.head()

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,BURN_PEDS,ACS_VERIFIED,ADULT_TRAUMA_L1,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE
0,Alaska,AK,Anchorage,4315 Diplomacy Dr,Anchorage,99508,6940010.0,Alaska Native Medical Center,173,NaN,...,NaN,Yes,NaN,1.0,NaN,1.0,NaN,Yes,NaN,(907) 563-2662
1,Alaska,AK,Anchorage,3200 Providence Dr,Anchorage,99508,6940020.0,Providence Alaska Medical Center/Children's Ho...,401,NaN,...,NaN,Yes,NaN,1.0,NaN,1.0,NaN,Yes,NaN,(907) 562-2211
2,Alabama,AL,Houston,1108 Ross Clark Cir,Dothan,36301,6530373.0,Southeast Alabama Medical Center,387,NaN,...,NaN,No,NaN,1.0,NaN,NaN,NaN,Yes,NaN,(334) 793-8111
3,Alabama,AL,Jefferson,619 19th St S,Birmingham,35233,6530304.0,University of Alabama at Birmingham Hospital (...,1157,28.0,...,NaN,Yes,1.0,NaN,NaN,NaN,No,Yes,No,(205) 934-3411
4,Alabama,AL,Jefferson,1600 7th Ave South,Birmingham,35233,6530170.0,Children's of Alabama (Children's of Alabama B...,351,6.0,...,1.0,No,NaN,NaN,1.0,NaN,No,Yes,No,(205) 638-9100

In [42]:
df_burn.columns

Index(['STATE_FULL', 'STATE', 'COUNTY', 'ADDRESS', 'CITY', 'ZIP_CODE',
       'AHA_ID', 'HOSPITAL_NAME', 'TOTAL_BEDS', 'BURN_BEDS', 'TRAUMA_ADULT',
       'TRAUMA_PEDS', 'BURN_ADULT', 'BURN_PEDS', 'ACS_VERIFIED',
       'ADULT_TRAUMA_L1', 'ADULT_TRAUMA_L2', 'PEDS_TRAUMA_L1',
       'PEDS_TRAUMA_L2', 'ABA_VERIFIED', 'TC_STATE_DESIGNATED',
       'BC_STATE_DESIGNATED', 'PHONE'],
      dtype='object')

In [43]:
df_burn['HOSPITAL_NAME'].unique()

array(['Alaska Native Medical Center',
       "Providence Alaska Medical Center/Children's Hospital at Providence",
       'Southeast Alabama Medical Center',
       'University of Alabama at Birmingham Hospital (UAB Burn Center)',
       "Children's of Alabama (Children's of Alabama Burn Center)",
       'Huntsville Hospital ',
       'USA Health University Hospital (Arnold Luterman Regional Burn Center)',
       'Baptist Medical Center South ', 'Flagstaff Medical Center',
       'Chandler Regional Medical Center',
       'Banner Thunderbird Medical Center', 'Abrazo West Campus',
       "Banner Desert Medical Center/Banner Children's at Desert",
       'Banner University Medical Center - Phoenix',
       "St. Joseph's Hospital and Medical Center",
       'HonorHealth Deer Valley Medical Center',
       'HonorHealth John C. Lincoln Medical Center',
       "Phoenix Children's Hospital",
       'Valleywise Health (Arizona Burn Center)',
       'HonorHealth Scottsdale Osborn Medical Center',
       'Banner University Medical Center - Tucson (Burn Unit at Banner)',
       "Carondelet St. Joseph's Hospital",
       'CHI St. Vincent Hospital Hot Springs',
       "Arkansas Children's Hospital (Arkansas Children's Hospital Burn Center)",
       'UAMS Medical Center', 'Baptist Health Medical Center',
       'CHI St. Vincent Infirmary ', 'Washington Regional Medical Center',
       'Highland Hospital', 'Sutter Health Eden Medical Center',
       "UCSF Benioff Children's Hospital Oakland", 'Enloe Medical Center',
       'John Muir Medical Center, Walnut Creek',
       'Community Regional Medical Center (Leon S. Peters Burn Center)',
       'The Grossman Burn Center at Bakersfield Memorial Hospital ',
       'Antelope Valley Hospital ', 'Cedar-Sinai Medical Center',
       "Children's Hospital Los Angeles",
       'Pomona Valley Hospital Medical Center',
       'St. Francis Medical Center Lynwood',
       'Providence Holy Cross Medical Center',
       'Ronald Reagan UCLA Medical Center',
       'The Grossman Burn Center at West Hills Hospital & Medical Center ',
       'Torrance Memorial Burn Center',
       'California Hospital Medical Center',
       'Northridge Hospital Medical Center', 'Harbor-UCLA Medical Center',
       'Henry Mayo Newhall Hospital', 'Huntington Hospital',
       'LAC + USC Medical Center (LAC + USC Regional Burn Center)',
       'Long Beach Medical Center', 'St. Mary Medical Center Long Beach',
       "Valley Children's Healthcare", 'Natividad Medical Center',
       'Providence Mission Hospital',
       'UC Irvine Health (UCI Regional Burn Center)',
       "Children's Hospital of Orange County",
       'Orange County Global Medical Center (Orange County Burn Center)',
       'Sutter Roseville Medical Center',
       'Desert Regional Medical Center',
       'HCA Riverside Community Hospital', 'Inland Valley Medical Center',
       'Riverside University Health System Medical Center',
       'Mercy San Juan Medical Center',
       'Kaiser Permanente South Sacramento Medical Center',
       'UC Davis Medical Center (UC Davis Regional Burn Center)',
       'Shriners Burn Center at Shriners Hospitals for Children - Nothern California',
       'Arrowhead Regional Medical Center (Edward G. Hirschman Burn Center)',
       "Loma Linda University Medical Center/Loma Linda University Children's Hospital",
       'Palomar Medical Center Escondido',
       "Rady Children's Hospital - San Diego",
       'Scripps Memorial Hospital', 'Scripps Mercy Hospital',
       'Sharp Memorial Hospital',
       'UC San Diego Medical Center (UCSD Regional Burn Center)',
       'Zuckerberg San Francisco General Hospital ',
       'Bothin Burn Center at St. Francis Memorial Hospital',
       'San Joaquin General Hospital',
       "Stanford Health Care/Lucile Packard Children's Hospital Stanford",
       'Santa Barbara Cottage Hospital',
       'Santa Clara Valley Medical Center (Santa Clara Valley Medical Center Regional Burn Center)',
       'HCA Regional Medical Center', 'Mercy Medical Center Redding',
       'Kaiser Permanente Vacaville Medical Center',
       'NorthBay Medical Center', 'Santa Rosa Memorial Hospital',
       'Doctors Medical Center', 'Memorial Medical Center',
       'Ventura County Medical Center ',
       'Los Robles Hospital and Medical Center',
       "Children's Hospital Colorado (Children's Hospital Colorado Burn Center)",
       'University of Colorado Hospital (Burn & Frostbite Center at UCHealth)',
       'North Suburban Medical Center',
       'Swedish Medical Center (Burn and Reconstructive Centers of Colorado)',
       'Medical Center of Aurora ', 'Littleton Adventist Hospital ',
       'Good Samaritan Medical Center',
       'Boulder Community Foothills Hospital',
       'Denver Health Medical Center', 'Sky Ridge Medical Center ',
       'Parker Adventist Hospital', 'Penrose Hospital',
       'UCHealth Memorial Hospital',
       "Children's Hospital of Colorado at Memorial",
       'St. Anthony Hospital', 'Lutheran Medical Center',
       'UCHealth Medical Center of the Rockies',
       "St. Mary's Hospital and Medical Center",
       'North Colorado Medical Center (Western States Burn Center)',
       'Bridgeport Hospital (The Connecticut Burn Center)',
       'Danbury Hospital', 'Norwalk Hospital',
       "St. Vincent's Medical Center ", 'Stamford Hospital',
       "Connecticut Children's Medical Center", 'Hartford Hospital',
       'Saint Francis Hospital and Medical Center',
       "Saint Mary's Hospital", 'Waterbury Hospital',
       'Yale-New Haven Hospital', 'Yale-New Haven Hospital-Saint Raphael',
       'ChristianaCare', "Nemours Children's Hospital ",
       'MedStar Washington Hospital Center (The Burn Center at MedStar Washington Hospital Center)',
       'George Washington University Hospital',
       'Howard University Hospital',
       "Children's National Health System (Children's National Trauma and Burn Center)",
       'UF Health Shands Hospital (UF Health Shands Burn Center)',
       'Ascension Sacred Heart Bay',
       'Health First Holmes Regional Medical Center',
       "Memorial Regional Hospital/Joe DiMaggio Children's Hospital",
       'Broward Health Medical Center', 'Broward Health North',
       'Orange Park Medical Center', 'Shands Jacksonville Medical Center',
       "Wolfson Children's Hospital", 'Baptist Hospital',
       'Ascension Sacred Heart Pensacola',
       'Tampa General Hospital (Tampa General Hospital Regional Burn Center)',
       "St. Joseph's Hospital", 'Lee Memorial Hospital',
       'Tallahassee Memorial HealthCare',
       'Blake Medical Center (Burn Center at Blake Medical Center)',
       'Ocala Regional Medical Center',
       'Kendall Regional Medical Center (Burn and Reconstructive Centers of FL)',
       'Jackson Memorial Hospital (Miami Burn Center)',
       "Nicklaus Children's Hospital",
       'Aventura Hospital and Medical Center',
       'Jackson South Community Hospital',
       'Fort Walton Beach Medical Center',
       'Orlando Regional Medical Center/Arnold Palmer Hospital for Children (Warden Burn Center)',
       'Osceola Regional Medical Center', 'Delray Medical Center',
       "St. Mary's Medical Center",
       'Regional Medical Center Bayonet Point',
       'Bayfront Health St. Petersburg',
       "Johns Hopkins All Children's Hospital ",
       'Lakeland Regional Medical Center',
       'Sarasota Memorial Health Care System',
       'Central Florida Regional Hospital',
       'Lawnwood Regional Medical Center',
       'Halifax Health Medical Center',
       'Florida Memorial Hospital (Jacksonville)',
       'Piedmont Athens Regional Medical Center',
       'WellStar Atlanta Medical Center',
       "Children's Healthcare of Atlanta at Egleston",
       'Grady Memorial Hospital (Grady Burn Center)',
       "Children's Healthcare of Atlanta at Scottish Rite",
       'Augusta University Medical Center',
       'Doctors Hospital of Augusta (Joseph M. Still Burn Center)',
       'Joseph M. Still Burn Center at WellStar Cobb Hospital ',
       'Piedmont Columbus Regional Midtown',
       'Northeast Georgia Medical Center',
       'Northside Hospital - Gwinnett',
       'Atrium Health Navicent The Medical Center',
       'WellStar Kennestone Hospital', 'Atrium Health Floyd',
       'WellStar North Fulton Hospital',
       'Memorial Health University Medical Center',
       "The Queen's Medical Center", 'Tripler Army Medical Center',
       'Straub Burn Center', 'Saint Alphonsus Regional Medical Center',
       'Portneuf Medical Center',
       'Eastern Idaho Regional Medical Center (Burn Center at EIRMC)',
       "St. Luke's Children's Hospital and Regional Medical Center",
       'Blessing Hospital', 'Carle Foundation Hospital\t',
       'Loyola University Medical Center (Loyola Burn Center)',
       'Advocate Christ Medical Center',
       'AMITA Health Adventist Medical Center La Grange',
       'Gottlieb Memorial Hospital', 'MacNeal Hospital\t',
       'Advocate Lutheran General Hospital',
       'AMITA Health Alexian Brothers Medical Center',
       'Northwest Community Healthcare',
       'AMITA Health St. Alexius Medical Center Hoffman Estates',
       'NorthShore Evanston Hospital', 'NorthShore Glenbrook Hospital',
       'AMITA Health Saint Francis Hospital Evanston',
       'Advocate Illinois Masonic Medical Center\t',
       "Ann & Robert H. Lurie Children's Hospital of Chicago\t",
       'John H. Stroger Jr. Hospital of Cook County (Sumner L. Koch Burn Center)',
       'Mount Sinai Hospital\t', 'Northwestern Memorial Hospital',
       'University of Chicago Medical Center (University of Chicago Burn Center)',
       'AMITA Health Adventist Medical Center GlenOaks',
       'AMITA Health Adventist Medical Center Hinsdale',
       'Advocate Good Samaritan Hospital\t',
       'Northwestern Medicine Central Dupage Hospital\t',
       'Edward Hospital\t', 'Elmhurst Memorial Hospital\t',
       'Memorial Hospital of Carbondale\t',
       "AMITA Health St. Mary's Hospital", 'Riverside Medical Center',
       'Advocate Sherman Hospital\t',
       'Northwestern Medicine Delnor Hospital',
       'AMITA Health Mercy Medical Center\t',
       'AMITA Health Saint Joseph Hospital\t',
       'Rush Copley Medical Center\t',
       'Advocate Good Shepherd Hospital\t',
       'Advocate Condell Medical Center\t',
       'NorthShore Highland Park Hospital',
       'Northwestern Medicine Lake Forest Hospital\t',
       'Vista Medical Center East\t', 'Decatur Memorial Hospital\t',
       'Morris Hospital & Healthcare Centers',
       'Northwestern Medicine Huntley',
       'Northwestern Medicine McHenry Hospital',
       'Carle BroMenn Medical Center', 'OSF St. Joseph Medical Center\t',
       "OSF St. Francis Medical Center/OSF Children's Hospital of Illinois\t",
       'UnityPoint Health - Methodist Hospital',
       'Genesis Medical Center, Silvis',
       'UnityPoint Health - Trinity Rock Island',
       'Memorial Medical Center (Regional Burn Center)',
       "St. John's Hospital/St. John's Children's Hospital\t",
       'Presence St. Joseph Medical Center\t', 'Silver Cross Hospital\t',
       'AMITA Health Adventist Medical Center Bolingbrook\t',
       'OSF Saint Anthony Medical Center (w/ Burn Unit)',
       'Mercyhealth Javon Bea Hospital - Riverside Campus',
       'SwedishAmerican - A Division of UW Health',
       'Lutheran Hospital (Lutheran Hospital Burn Center)',
       'Parkview Regional Medical Center',
       "Ascension St. Vincent Indianapolis Hospital/Peyton Manning Children's Hospital (Burn Center)",
       'Eskenazi Health (Richard M. Fairbanks Burn Center)',
       'Indiana University Health Methodist Hospital',
       'Riley Hospital for Children at Indiana University Health (Burn Program at Riley IU Health)',
       'Memorial Hospital of South Bend',
       'Ascension St. Vincent Evansville', 'Deaconess Midtown Hospital',
       "University of Iowa Hospitals and Clinics/Stead Family Children's Hospital (UI Burn Center)",
       "UnityPoint Health - Iowa Methodist Medical Center/Blank Children's Hospital",
       'MercyOne Des Moines Medical Center',
       'MercyOne Siouxland Medical Center',
       'Overland Park Regional Medical Center',
       'Ascension Via Christi St. Francis (Ascension Via Christi Regional Burn Center)',
       "Wesley Healthcare Center/Wesley Children's Hospital",
       'Stormont Vail Health',
       'The University of Kansas Hospital (Burnett Burn Center)',
       'University of Kentucky Albert B. Chandler Hospital ',
       "Norton Children's Hospital",
       'UL Hospital (University of Louisville Burn Center)',
       'Pikeville Medical Center',
       'Ochsner LSU Health Shreveport (LSU Health Burn Center)',
       'Our Lady of the Lake Regional Medical Center',
       'Baton Rouge General Regional Burn Center',
       'Ochsner Lafayette General Medical Center',
       'Grossman Burn Center at Our Lady of Lourdes Regional Medical Center',
       'University Medical Center New Orleans (UMC Burn Center)',
       'Rapides Regional Medical Center - Alexandria',
       'Lakeview Regional Medical Center', 'North Oaks Medical Center',
       'Maine Medical Center (Maine Medical Center Burn Unit)',
       'Northern Light Eastern Maine Medical Center',
       'Johns Hopkins Hospital (Johns Hopkins Pediatric Burn Center)',
       'Johns Hopkins Bayview Medical Center (Johns Hopkins Adult Burn Center)',
       'Sinai Hospital of Baltimore',
       'Walter Reed National Military Medical Center',
       'Suburban Hospital',
       'University of Maryland Capital Region Medical Center',
       "St. Luke's Hospital", 'Baystate Medical Center',
       'Lahey Hospital & Medical Center, Burlington',
       'South Shore Hospital', 'Beth Israel Deaconess Medical Center',
       "Boston Children's Hospital", 'Boston Medical Center',
       "Brigham and Women's Hospital (Burn Center)",
       'Massachusetts General Hospital (Sumner M. Redstone Burn Center)',
       'Tufts Medical Center',
       'Shriners Burn Center at Shriners Hospitals for Children-Boston',
       'McLaren Northern Michigan', 'Ascension Genesys Hospital',
       "Hurley Medical Center/Hurley Children's Hospital (Hurley Medical Center Regional Burn Center)",
       'Munson Medical Center', 'Sparrow Hospital',
       'Henry Ford Allegiance Health', 'Ascension Borgess Hospital',
       'Bronson Methodist Hospital (Bronson Methodist Hospital Burn Center)',
       "Mercy Health Saint Mary's",
       "Spectrum Health - Butterworth Hospital/Helen DeVos Children's Hospital (Spectrum Health Regional Burn Center)",
       'Metro Health - University of Michigan Health',
       'McLaren Lapeer Region', 'Henry Ford Macomb Hospital',
       'McLaren Macomb Hospital', 'UP Health System-Marquette',
       'MidMichigan Medical Center-Midland', 'Mercy Health Muskegon',
       'Ascension Providence Hospital, Southfield Campus',
       'Providence Park Hospital, Novi Campus',
       'Beaumont Hospital - Troy', 'Beaumont Hospital - Royal Oak',
       'Beaumont Hospital - Farmington Hills', 'McLaren Oakland',
       'St. Joseph Mercy Oakland', "Ascension St. Mary's of Michigan",
       'Covenant HealthCare', 'St. Joseph Mercy Ann Arbor',
       "University of Michigan Health System/C.S. Mott Children's Hospital (UM Trauma Burn Center)",
       'Ascension St. John Hospital', 'Beaumont Hospital - Trenton',
       'Beaumont Hospital - Dearborn',
       "DMC - Children's Hospital of Michigan (Children's Hospital of Michigan Burn Center)",
       'DMC - Sinai-Grace Hospital',
       'Detroit Receiving Hospital (Detroit Receiving Hospital Burn Center)',
       'Henry Ford Hospital', 'St. Mary Mercy Livonia Hospital',
       'Mercy Hospital', "Essentia Health St. Mary's Medical Center",
       'Miller-Dwan Burn Center at Essentia Health Duluth',
       "Children's Hospital and Clinics of Minnesota",
       "Hennepin Healthcare/Hennepin Healthcare Children's Hospital (Hennepin Healthcare Burn Center)",
       'University of Minnesota Medical Center',
       'North Memorial Health Hospital',
       "Mayo Clinic Hospital, Saint Mary's Campus",
       'CentraCare - St. Cloud Hospital',
       "Regions Hospital/Gillette Children's Specialty Healthcare (Regions Hospital Burn Center)",
       'Forrest General Hospital', 'Memorial Hospital at Gulfport',
       'University of Mississippi Medical Center',
       'North Mississippi Medical Center - Tupelo',
       'University of Missouri Health System (George D. Peak Memorial Burn & Wound Center)',
       'Mosaic Life Care at St. Joseph - Medical Center',
       'Liberty Hospital', 'North Kansas City Hospital',
       'Cox Medical Center South',
       'Mercy Hospital Springfield (Mercy Burn Center Springfield)',
       "Children's Mercy Kansas City (Children's Mercy Burn Unit)",
       'HCA Research Medical Center (The Grossman Burn Center)',
       'University Health Truman Medical Center',
       "St. Luke's Hospital of Kansas City", 'Centerpoint Medical Center',
       'Freeman Health System', 'Mercy Hospital Joplin',
       'SSM Health DePaul Hospital - St. Louis', 'Mercy Hospital South',
       'Barnes-Jewish Hospital (Burn Center)',
       'SSM Health St. Louis University Hospital',
       "St. Louis Children's Hospital (Children's Hospital Burn Center)",
       'Mercy Hospital St. Louis (Mercy Burn Center St. Louis)',
       "SSM Cardinal Glennon Children's Hospital", 'Benefis Hospitals',
       'Providence St. Patrick Hospital', 'Billings Clinic',
       'SCL Health - St. Vincent Healthcare', 'CHI Health Good Samaritan',
       'CHI Health Creighton University Medical Center - Bergan Mercy',
       "Children's Hospital & Medical Center",
       'Nebraska Medicine - Nebraska Medical Center',
       'Bryan Medical Center West',
       'CHI Health St. Elizabeth Regional Burn Center',
       'Regional West Medical Center',
       'Sunrise Hospital and Medical Center (Burn and Reconstructive Center of Sunrise Hospital)',
       'University Medical Center (Lions Burn Center)',
       'Renown Regional Medical Center',
       'Dartmouth-Hitchcock Medical Center', 'Concord Hospital',
       'Elliot Hospital', 'Portsmouth Regional Hospital',
       'AtlantiCare Regional Medical Center',
       'Hackensack University Medical Center',
       'Cooper University Health Care',
       'New Jersey Trauma Center at the University Hospital',
       'The Burn Center at Cooperman Barnabas Medical Center',
       'Jersey City Medical Center - RWJBarnabas Health',
       'Capital Health Regional Medical Center',
       'Robert Wood Johnson University Hospital',
       'Jersey Shore University Medical Center',
       'Morristown Medical Center',
       "St. Joseph's University Medical Center",
       'University of New Mexico Hospital (UNM Regional Burn Center)',
       'Albany Medical Center',
       'NYC Health + Hospitals / Lincoln Medical & Mental Health Center',
       'NYC Health + Hospitals / Jacobi Medical Center (Jacobi Burn Center)',
       'St. Barnabas Hospital', 'UHS Wilson Medical Center',
       'Mid Hudson Regional Hospital of Westchester Medical Center',
       'Vassar Brothers Medical Center',
       'Erie County Medical Center (Roger W. Seibel, MD, Burn Treatment Center)',
       "John R. Oishei Children's Hospital",
       'Brookdale Hospital Medical Center',
       "Maimonides Medical Center/Maimonides Children's Hospital",
       'NewYork Presbyterian Brooklyn Methodist Hospital',
       'NYC Health + Hospitals / Kings County',
       'NYU Langone Hospital-Brooklyn ',
       'University of Rochester Medical Center/Strong Memorial Hospital (Kessler Burn Center)',
       'Mount Sinai South Nassau',
       'Nassau University Medical Center (Nassau County Firefighters Burn Center)',
       "Cohen Children's Medical Center",
       'North Shore University Hospital',

## Cleaning of Data

### Replace the nan with 0 in various columns

In [44]:
def replace_nan_with_0(df_d):
  df_d.fillna(0, inplace=True)
  return df_d

In [45]:
df_burn['ADULT_TRAUMA_L1']

0      NaN
1      NaN
2      NaN
3      1.0
4      NaN
      ...
630    NaN
631    NaN
632    NaN
633    NaN
634    NaN
Name: ADULT_TRAUMA_L1, Length: 635, dtype: float64

In [46]:
replace_nan_with_0(df_burn['ADULT_TRAUMA_L1'])

0      0.0
1      0.0
2      0.0
3      1.0
4      0.0
      ...
630    0.0
631    0.0
632    0.0
633    0.0
634    0.0
Name: ADULT_TRAUMA_L1, Length: 635, dtype: float64

In [47]:
replace_nan_with_0(df_burn['ADULT_TRAUMA_L2'])

0      1.0
1      1.0
2      1.0
3      0.0
4      0.0
      ...
630    0.0
631    1.0
632    1.0
633    1.0
634    1.0
Name: ADULT_TRAUMA_L2, Length: 635, dtype: float64

In [48]:
df_burn.head()

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,BURN_PEDS,ACS_VERIFIED,ADULT_TRAUMA_L1,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE
0,Alaska,AK,Anchorage,4315 Diplomacy Dr,Anchorage,99508,6940010.0,Alaska Native Medical Center,173,NaN,...,NaN,Yes,0.0,1.0,NaN,1.0,NaN,Yes,NaN,(907) 563-2662
1,Alaska,AK,Anchorage,3200 Providence Dr,Anchorage,99508,6940020.0,Providence Alaska Medical Center/Children's Ho...,401,NaN,...,NaN,Yes,0.0,1.0,NaN,1.0,NaN,Yes,NaN,(907) 562-2211
2,Alabama,AL,Houston,1108 Ross Clark Cir,Dothan,36301,6530373.0,Southeast Alabama Medical Center,387,NaN,...,NaN,No,0.0,1.0,NaN,NaN,NaN,Yes,NaN,(334) 793-8111
3,Alabama,AL,Jefferson,619 19th St S,Birmingham,35233,6530304.0,University of Alabama at Birmingham Hospital (...,1157,28.0,...,NaN,Yes,1.0,0.0,NaN,NaN,No,Yes,No,(205) 934-3411
4,Alabama,AL,Jefferson,1600 7th Ave South,Birmingham,35233,6530170.0,Children's of Alabama (Children's of Alabama B...,351,6.0,...,1.0,No,0.0,0.0,1.0,NaN,No,Yes,No,(205) 638-9100

In [49]:
replace_nan_with_0(df_burn['PEDS_TRAUMA_L1'])

0      0.0
1      0.0
2      0.0
3      0.0
4      1.0
      ...
630    0.0
631    0.0
632    0.0
633    0.0
634    0.0
Name: PEDS_TRAUMA_L1, Length: 635, dtype: float64

In [50]:
replace_nan_with_0(df_burn['PEDS_TRAUMA_L2'])

0      1.0
1      1.0
2      0.0
3      0.0
4      0.0
      ...
630    0.0
631    0.0
632    0.0
633    0.0
634    1.0
Name: PEDS_TRAUMA_L2, Length: 635, dtype: float64

In [51]:
replace_nan_with_0(df_burn['TRAUMA_ADULT'])

0      1.0
1      1.0
2      1.0
3      1.0
4      0.0
      ...
630    0.0
631    1.0
632    1.0
633    1.0
634    1.0
Name: TRAUMA_ADULT, Length: 635, dtype: float64

In [52]:
replace_nan_with_0(df_burn['TRAUMA_PEDS'])

0      1.0
1      1.0
2      0.0
3      0.0
4      1.0
      ...
630    0.0
631    0.0
632    0.0
633    0.0
634    1.0
Name: TRAUMA_PEDS, Length: 635, dtype: float64

In [53]:
replace_nan_with_0(df_burn['BURN_ADULT'])

0      0.0
1      0.0
2      0.0
3      1.0
4      0.0
      ...
630    1.0
631    0.0
632    0.0
633    0.0
634    0.0
Name: BURN_ADULT, Length: 635, dtype: float64

In [54]:
replace_nan_with_0(df_burn['BURN_PEDS'])

0      0.0
1      0.0
2      0.0
3      0.0
4      1.0
      ...
630    1.0
631    0.0
632    0.0
633    0.0
634    0.0
Name: BURN_PEDS, Length: 635, dtype: float64

In [55]:
df_burn.head()

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,BURN_PEDS,ACS_VERIFIED,ADULT_TRAUMA_L1,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE
0,Alaska,AK,Anchorage,4315 Diplomacy Dr,Anchorage,99508,6940010.0,Alaska Native Medical Center,173,NaN,...,0.0,Yes,0.0,1.0,0.0,1.0,NaN,Yes,NaN,(907) 563-2662
1,Alaska,AK,Anchorage,3200 Providence Dr,Anchorage,99508,6940020.0,Providence Alaska Medical Center/Children's Ho...,401,NaN,...,0.0,Yes,0.0,1.0,0.0,1.0,NaN,Yes,NaN,(907) 562-2211
2,Alabama,AL,Houston,1108 Ross Clark Cir,Dothan,36301,6530373.0,Southeast Alabama Medical Center,387,NaN,...,0.0,No,0.0,1.0,0.0,0.0,NaN,Yes,NaN,(334) 793-8111
3,Alabama,AL,Jefferson,619 19th St S,Birmingham,35233,6530304.0,University of Alabama at Birmingham Hospital (...,1157,28.0,...,0.0,Yes,1.0,0.0,0.0,0.0,No,Yes,No,(205) 934-3411
4,Alabama,AL,Jefferson,1600 7th Ave South,Birmingham,35233,6530170.0,Children's of Alabama (Children's of Alabama B...,351,6.0,...,1.0,No,0.0,0.0,1.0,0.0,No,Yes,No,(205) 638-9100

In [56]:
df_burn['BURN_BEDS'].isnull().sum()

np.int64(505)

In [57]:
df_burn['BURN_ADULT']

0      0.0
1      0.0
2      0.0
3      1.0
4      0.0
      ...
630    1.0
631    0.0
632    0.0
633    0.0
634    0.0
Name: BURN_ADULT, Length: 635, dtype: float64

In [58]:
df_burn.head()

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,BURN_PEDS,ACS_VERIFIED,ADULT_TRAUMA_L1,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE
0,Alaska,AK,Anchorage,4315 Diplomacy Dr,Anchorage,99508,6940010.0,Alaska Native Medical Center,173,NaN,...,0.0,Yes,0.0,1.0,0.0,1.0,NaN,Yes,NaN,(907) 563-2662
1,Alaska,AK,Anchorage,3200 Providence Dr,Anchorage,99508,6940020.0,Providence Alaska Medical Center/Children's Ho...,401,NaN,...,0.0,Yes,0.0,1.0,0.0,1.0,NaN,Yes,NaN,(907) 562-2211
2,Alabama,AL,Houston,1108 Ross Clark Cir,Dothan,36301,6530373.0,Southeast Alabama Medical Center,387,NaN,...,0.0,No,0.0,1.0,0.0,0.0,NaN,Yes,NaN,(334) 793-8111
3,Alabama,AL,Jefferson,619 19th St S,Birmingham,35233,6530304.0,University of Alabama at Birmingham Hospital (...,1157,28.0,...,0.0,Yes,1.0,0.0,0.0,0.0,No,Yes,No,(205) 934-3411
4,Alabama,AL,Jefferson,1600 7th Ave South,Birmingham,35233,6530170.0,Children's of Alabama (Children's of Alabama B...,351,6.0,...,1.0,No,0.0,0.0,1.0,0.0,No,Yes,No,(205) 638-9100

In [59]:
df_burn['ABA_VERIFIED'].isnull().sum()

np.int64(492)

## Seperating the centers to non burn centers and burn centers

In [60]:
df_non_burn_center = df_burn[(df_burn['BURN_ADULT']==0) & (df_burn['BURN_PEDS']==0)].copy()

In [61]:
df_non_burn_center.shape

(499, 23)

In [62]:
df_burn_center = df_burn[(df_burn['BURN_ADULT']==1) | (df_burn['BURN_PEDS']== 1)].copy()

In [63]:
df_burn_center.shape

(136, 23)

# Prepare the address for transformation into Longitude and Latitude


We are going to prepare the address by combing the various components of 'ADDRESS','CITY','STATE_FULL' AND 'ZIPCODE' into single string add it to it's own column and geocode it to get the longitude and latitude.

## Prepare Address for Geocoding

### Subtask:
Select the specific row(s) you are interested in from the dataframes or burn and non burn centers and combine the address components (ADDRESS, CITY, STATE_FULL, ZIP_CODE) into a single, complete address string. This combined string will be used for geocoding.

**Reasoning**:
The subtask requires creating a new column `FULL_ADDRESS` in `df_burn_center`and `non_burn_center` by concatenating the address components. This step will achieve that by combining the specified columns with the correct delimiters.

In [64]:
df_burn_center['FULL_ADDRESS'] = df_burn_center['ADDRESS'] + ', ' + df_burn_center['CITY'] + ', ' + df_burn_center['STATE_FULL'] + ' ' + df_burn_center['ZIP_CODE'].astype(str)
df_burn_center.head()

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,ACS_VERIFIED,ADULT_TRAUMA_L1,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE,FULL_ADDRESS
3,Alabama,AL,Jefferson,619 19th St S,Birmingham,35233,6530304.0,University of Alabama at Birmingham Hospital (...,1157,28.0,...,Yes,1.0,0.0,0.0,0.0,No,Yes,No,(205) 934-3411,"619 19th St S, Birmingham, Alabama 35233"
4,Alabama,AL,Jefferson,1600 7th Ave South,Birmingham,35233,6530170.0,Children's of Alabama (Children's of Alabama B...,351,6.0,...,No,0.0,0.0,1.0,0.0,No,Yes,No,(205) 638-9100,"1600 7th Ave South, Birmingham, Alabama 35233"
6,Alabama,AL,Mobile,2451 University Hospital Dr,Mobile,36617,6530600.0,USA Health University Hospital (Arnold Luterma...,214,18.0,...,No,1.0,0.0,0.0,0.0,No,Yes,No,(251) 471-7000,"2451 University Hospital Dr, Mobile, Alabama 3..."
18,Arizona,AZ,Maricopa,2601 E Roosevelt St,Phoenix,85008,6860255.0,Valleywise Health (Arizona Burn Center),544,45.0,...,Yes,1.0,0.0,0.0,0.0,Yes,Yes,No,(602) 344-5011,"2601 E Roosevelt St, Phoenix, Arizona 85008"
20,Arizona,AZ,Pima,1501 N Campbell Ave,Tucson,85719,6860516.0,Banner University Medical Center - Tucson (Bur...,584,35.0,...,Yes,1.0,0.0,0.0,1.0,No,Yes,No,(520) 694-0111,"1501 N Campbell Ave, Tucson, Arizona 85719"

In [65]:
df_non_burn_center['FULL_ADDRESS'] = df_non_burn_center['ADDRESS'] + ', ' + df_non_burn_center['CITY'] + ', ' + df_non_burn_center['STATE_FULL'] + ' ' + df_non_burn_center['ZIP_CODE'].astype(str)
df_non_burn_center.head()

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,ACS_VERIFIED,ADULT_TRAUMA_L1,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE,FULL_ADDRESS
0,Alaska,AK,Anchorage,4315 Diplomacy Dr,Anchorage,99508,6940010.0,Alaska Native Medical Center,173,NaN,...,Yes,0.0,1.0,0.0,1.0,NaN,Yes,NaN,(907) 563-2662,"4315 Diplomacy Dr, Anchorage, Alaska 99508"
1,Alaska,AK,Anchorage,3200 Providence Dr,Anchorage,99508,6940020.0,Providence Alaska Medical Center/Children's Ho...,401,NaN,...,Yes,0.0,1.0,0.0,1.0,NaN,Yes,NaN,(907) 562-2211,"3200 Providence Dr, Anchorage, Alaska 99508"
2,Alabama,AL,Houston,1108 Ross Clark Cir,Dothan,36301,6530373.0,Southeast Alabama Medical Center,387,NaN,...,No,0.0,1.0,0.0,0.0,NaN,Yes,NaN,(334) 793-8111,"1108 Ross Clark Cir, Dothan, Alabama 36301"
5,Alabama,AL,Madison,101 Sivley Rd,Huntsville,35801,6530510.0,Huntsville Hospital,958,NaN,...,No,1.0,0.0,0.0,0.0,NaN,Yes,NaN,(256) 265-1000,"101 Sivley Rd, Huntsville, Alabama 35801"
7,Alabama,AL,Montgomery,2105 E South Blvd,Montgomery,36116,6530705.0,Baptist Medical Center South,492,NaN,...,No,0.0,1.0,0.0,0.0,NaN,Yes,NaN,(334) 288-2100,"2105 E South Blvd, Montgomery, Alabama 36116"

In [66]:
# df_burn_center = df_burn[(df_burn['BURN_ADULT']==1) | (df_burn['BURN_PEDS']== 1)].copy()

# Geocode the addresses

##Burn Center Geocoding

In [67]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="burn_center_locator")
print("Geolocator initialized.")

Geolocator initialized.

In [68]:
import time
from geopy.geocoders import Nominatim

# Re-initialize geolocator with a longer timeout (e.g., 5 seconds)
geolocator = Nominatim(user_agent="burn_center_locator", timeout=5)

latitudes = []
longitudes = []

for address in df_burn_center['FULL_ADDRESS']:
    try:
        location = geolocator.geocode(address)
        if location:
            latitudes.append(location.latitude)
            longitudes.append(location.longitude)
        else:
            latitudes.append(None)
            longitudes.append(None)
    except Exception as e:
        print(f"Error geocoding {address}: {e}")
        latitudes.append(None)
        longitudes.append(None)
    time.sleep(2) # Keep the 2-second delay to respect usage policy

df_burn_center['Latitude'] = latitudes
df_burn_center['Longitude'] = longitudes

df_burn_center.head()

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE,FULL_ADDRESS,Latitude,Longitude
3,Alabama,AL,Jefferson,619 19th St S,Birmingham,35233,6530304.0,University of Alabama at Birmingham Hospital (...,1157,28.0,...,0.0,0.0,0.0,No,Yes,No,(205) 934-3411,"619 19th St S, Birmingham, Alabama 35233",33.506101,-86.801782
4,Alabama,AL,Jefferson,1600 7th Ave South,Birmingham,35233,6530170.0,Children's of Alabama (Children's of Alabama B...,351,6.0,...,0.0,1.0,0.0,No,Yes,No,(205) 638-9100,"1600 7th Ave South, Birmingham, Alabama 35233",33.504689,-86.805635
6,Alabama,AL,Mobile,2451 University Hospital Dr,Mobile,36617,6530600.0,USA Health University Hospital (Arnold Luterma...,214,18.0,...,0.0,0.0,0.0,No,Yes,No,(251) 471-7000,"2451 University Hospital Dr, Mobile, Alabama 3...",30.707441,-88.101820
18,Arizona,AZ,Maricopa,2601 E Roosevelt St,Phoenix,85008,6860255.0,Valleywise Health (Arizona Burn Center),544,45.0,...,0.0,0.0,0.0,Yes,Yes,No,(602) 344-5011,"2601 E Roosevelt St, Phoenix, Arizona 85008",33.458477,-112.023581
20,Arizona,AZ,Pima,1501 N Campbell Ave,Tucson,85719,6860516.0,Banner University Medical Center - Tucson (Bur...,584,35.0,...,0.0,0.0,1.0,No,Yes,No,(520) 694-0111,"1501 N Campbell Ave, Tucson, Arizona 85719",32.241234,-110.945604

**Reasoning**:
To ensure all addresses were successfully geocoded as per the subtask's objective, I will check if there are any remaining null values in the 'Latitude' and 'Longitude' columns. If there are no null values, it means the geocoding process was successful for all entries.

In [69]:
print(f"Nulls in Latitude: {df_burn_center['Latitude'].isnull().sum()}")
print(f"Nulls in Longitude: {df_burn_center['Longitude'].isnull().sum()}")

Nulls in Latitude: 5
Nulls in Longitude: 5

Droping the 5 addresses that could not be geocoded

In [70]:
df_burn_center.dropna(subset=['Latitude', 'Longitude'], inplace=True)
print(f"Number of burn centers after dropping un-geocoded: {len(df_burn_center)}")
print(f"Nulls in Latitude after cleanup: {df_burn_center['Latitude'].isnull().sum()}")
print(f"Nulls in Longitude after cleanup: {df_burn_center['Longitude'].isnull().sum()}")
df_burn_center.head()

Number of burn centers after dropping un-geocoded: 131
Nulls in Latitude after cleanup: 0
Nulls in Longitude after cleanup: 0

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE,FULL_ADDRESS,Latitude,Longitude
3,Alabama,AL,Jefferson,619 19th St S,Birmingham,35233,6530304.0,University of Alabama at Birmingham Hospital (...,1157,28.0,...,0.0,0.0,0.0,No,Yes,No,(205) 934-3411,"619 19th St S, Birmingham, Alabama 35233",33.506101,-86.801782
4,Alabama,AL,Jefferson,1600 7th Ave South,Birmingham,35233,6530170.0,Children's of Alabama (Children's of Alabama B...,351,6.0,...,0.0,1.0,0.0,No,Yes,No,(205) 638-9100,"1600 7th Ave South, Birmingham, Alabama 35233",33.504689,-86.805635
6,Alabama,AL,Mobile,2451 University Hospital Dr,Mobile,36617,6530600.0,USA Health University Hospital (Arnold Luterma...,214,18.0,...,0.0,0.0,0.0,No,Yes,No,(251) 471-7000,"2451 University Hospital Dr, Mobile, Alabama 3...",30.707441,-88.101820
18,Arizona,AZ,Maricopa,2601 E Roosevelt St,Phoenix,85008,6860255.0,Valleywise Health (Arizona Burn Center),544,45.0,...,0.0,0.0,0.0,Yes,Yes,No,(602) 344-5011,"2601 E Roosevelt St, Phoenix, Arizona 85008",33.458477,-112.023581
20,Arizona,AZ,Pima,1501 N Campbell Ave,Tucson,85719,6860516.0,Banner University Medical Center - Tucson (Bur...,584,35.0,...,0.0,0.0,1.0,No,Yes,No,(520) 694-0111,"1501 N Campbell Ave, Tucson, Arizona 85719",32.241234,-110.945604

## Non Burn center decoding

In [71]:
from geopy.geocoders import Nominatim
import time

# Initialize geolocator
geolocator = Nominatim(user_agent="df_non_burn_center", timeout=10)

latitudes = []
longitudes = []

for i, address in enumerate(df_non_burn_center['FULL_ADDRESS']):
    try:
        if pd.isna(address):
            latitudes.append(None)
            longitudes.append(None)
            continue

        location = geolocator.geocode(address)

        if location is not None:
            latitudes.append(location.latitude)
            longitudes.append(location.longitude)
        else:
            latitudes.append(None)
            longitudes.append(None)

        print(f"{i+1}/{len(df_non_burn_center)} Geocoded: {address}")

    except Exception as e:
        print(f"Error geocoding {address}: {e}")
        latitudes.append(None)
        longitudes.append(None)

    time.sleep(2)  # Respect Nominatim rate limits

df_non_burn_center['Latitude'] = latitudes
df_non_burn_center['Longitude'] = longitudes

df_non_burn_center.head()

1/499 Geocoded: 4315 Diplomacy Dr, Anchorage, Alaska 99508
2/499 Geocoded: 3200 Providence Dr, Anchorage, Alaska 99508
3/499 Geocoded: 1108 Ross Clark Cir, Dothan, Alabama 36301
4/499 Geocoded: 101 Sivley Rd, Huntsville, Alabama 35801
5/499 Geocoded: 2105 E South Blvd, Montgomery, Alabama 36116
6/499 Geocoded: 1200 N Beaver St, Flagstaff, Arizona 86001
7/499 Geocoded: 1955 W Frye Rd, Chandler, Arizona 85224
8/499 Geocoded: 5555 W Thunderbird Rd, Glendale, Arizona 85306
9/499 Geocoded: 13677 W McDowell Rd, Goodyear, Arizona 85395
10/499 Geocoded: 1400 S Dobson Rd, Mesa, Arizona 85202
11/499 Geocoded: 1111 E McDowell Rd, Phoenix, Arizona 85006
12/499 Geocoded: 350 W Thomas Rd, Phoenix, Arizona 85013
13/499 Geocoded: 19829 North 27th Ave, Phoenix, Arizona 85027
14/499 Geocoded: 250 E Dunlap Ave, Phoenix, Arizona 85020
15/499 Geocoded: 1919 E Thomas Rd, Phoenix, Arizona 85016
16/499 Geocoded: 7400 E Osborn Rd, Scottsdale, Arizona 85251
17/499 Geocoded: 350 N Wilmot Rd, Tucson, Arizona 85718
18/499 Geocoded: 300 Werner St, Hot Springs, Arkansas 71913
19/499 Geocoded: 4301 W Markham St, Little Rock , Arkansas 72205
20/499 Geocoded: 9601 Baptist Health Dr, Little Rock, Arkansas 72205
21/499 Geocoded: 2 St Vincent Circle, Little Rock, Arkansas 72205
22/499 Geocoded: 3215 N Northhills Blvd, Fayetteville, Arkansas 72703
23/499 Geocoded: 1411 East 31st St, Oakland, California 94602
24/499 Geocoded: 20103 Lake Chabot Rd, Castro Valley, California 94546
25/499 Geocoded: 747 52nd St, Oakland, California 94609
26/499 Geocoded: 1531 Esplanade, Chico, California 95926
27/499 Geocoded: 1601 Ygnacio Valley Rd, Walnut Creek, California 94598
28/499 Geocoded: 1600 West Avenue J, Lancaster, California 93534
29/499 Geocoded: 8700 Beverly Blvd, West Hollywood, California 90048
30/499 Geocoded: 4650 Sunset Blvd, Los Angeles , California 90027
31/499 Geocoded: 1798 North Garey Ave, Pomona, California 91767
32/499 Geocoded: 3630 East Imperial Hwy, Lynwood, California 90262
33/499 Geocoded: 15031 Rinaldi St, Mission Hills, California 91345
34/499 Geocoded: 757 Westwood Plaza, Los Angeles, California 90095
35/499 Geocoded: 1401 S Grand Ave, Los Angeles, California 90015
36/499 Geocoded: 18300 Roscoe Blvd, Northridge , California 91335
37/499 Geocoded: 1000 W Carson St, Torrance, California 90502
38/499 Geocoded: 23845 McBean Pkwy, Valencia, California 91355
39/499 Geocoded: 100 W California Blvd, Pasadena, California 91105
40/499 Geocoded: 2801 Atlantic Ave, Long Beach, California 90806
41/499 Geocoded: 1050 Linden Ave, Long Beach, California 90813
42/499 Geocoded: 9300 Valley Children's Place, Madera, California 93636
43/499 Geocoded: 1441 Constitution Blvd, Salinas , California 93906
44/499 Geocoded: 27700 Medical Center Rd, Mission Viejo, California 92691
45/499 Geocoded: 1201 West La Veta Ave, Orange, California 92868
46/499 Geocoded: 1 Medical Plaza Dr, Roseville, California 95661
47/499 Geocoded: 1150 N Indian Canyon Dr, Palm Springs, California 92262
48/499 Geocoded: 4445 Magnolia Ave, Riverside , California 92501
49/499 Geocoded: 36485 Inland Valley Rd, Wildomar, California 92595
50/499 Geocoded: 26520 Cactus Avenue, Moreno Valley, California 92555
51/499 Geocoded: 6501 Coyle Ave, Carmichael, California 95608
52/499 Geocoded: 6600 Bruceville Rd, Sacramento, California 95823
53/499 Geocoded: 11234 Anderson St, Loma Linda, California 92354
54/499 Geocoded: 2185 West Citracado Pkwy, Escondido, California 92029
55/499 Geocoded: 3020 Children's Way, San Diego, California 92123
56/499 Geocoded: 9888 Genessee Ave, La Jolla, California 92037
57/499 Geocoded: 4077 5th Ave, San Diego, California 92103
58/499 Geocoded: 7901 Frost St, San Diego, California 92123
59/499 Geocoded: 1001 Potrero Ave, San Francisco, California 94110
60/499 Geocoded: 500 West Hospital Rd, French Camp, California 95231
61/499 Geocoded: 300 Pasteur Dr, Palo Alto, California 94305
62/499 Geocoded: 400 W Pueblo St, Santa Barbara, California 93105
63/499 Geocoded: 225 N Jackson Ave, San Jose, California 95116
64/499 Geocoded: 2175 Rosaline Ave, Redding, California 96001
65/499 Geocoded: 1 Quality Dr, Vacaville, California 95688
66/499 Geocoded: 1200 B. Gale Wilson Blvd, Fairfield, California 94533
67/499 Geocoded: 1165 Montgomery Dr, Santa Rosa, California 95405
68/499 Geocoded: 1441 Florida Ave, Modesto, California 95350
69/499 Geocoded: 1700 Coffee Rd, Modesto, California 95355
70/499 Geocoded: 300 Hillmont Ave, Ventura, California 93003
71/499 Geocoded: 215 West Janss Rd, Thousand Oaks, California 91360
72/499 Geocoded: 9191 Grant St, Thornton, Colorado 80229
73/499 Geocoded: 1501 South Potomac St, Aurora, Colorado 80012
74/499 Geocoded: 7700 S Broadway St, Littleton, Colorado 80122
75/499 Geocoded: 200 Exempla Circle, Lafayette , Colorado 80026
76/499 Geocoded: 4747 Arapahoe Ave, Boulder, Colorado 80304
77/499 Geocoded: 777 Bannock St, Denver, Colorado 80204
78/499 Geocoded: 10101 Ridge Gale Pkwy, Lone Tree, Colorado 80124
79/499 Geocoded: 9395 Crown Crest Blvd, Parker, Colorado 80138
80/499 Geocoded: 2222 N Nevada Ave, Colorado Springs, Colorado 80907
81/499 Geocoded: 1400 E Boulder St, Colorado Springs, Colorado 80909
82/499 Geocoded: 4090 Briargate Pkwy, Colorado Springs, Colorado 80920
83/499 Geocoded: 11600 W 2nd Pl, Lakewood, Colorado 80228
84/499 Geocoded: 8300 W 38th Ave, Wheat Ridge, Colorado 80033
85/499 Geocoded: 2500 Rocky Mountain Ave, Loveland, Colorado 80538
86/499 Geocoded: 2635 N 7th St, Grand Junction, Colorado 81501
87/499 Geocoded: 24 Hospital Ave, Danbury, Connecticut 6810
88/499 Geocoded: 34 Maple St, Norwalk, Connecticut 6856
Error geocoding 2800 Main St, Bridgeport, Connecticut 6606: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out.
90/499 Geocoded: 1 Hospital Plz, Stamford, Connecticut 6904
91/499 Geocoded: 282 Washington St, Hartford, Connecticut 6106
92/499 Geocoded: 80 Seymour St, Hartford, Connecticut 6102
93/499 Geocoded: 114 Woodland St, Hartford, Connecticut 6105
94/499 Geocoded: 56 Franklin St, Waterbury, Connecticut 6706
95/499 Geocoded: 64 Robbins St, Waterbury, Connecticut 6708
96/499 Geocoded: 20 York St, New Haven, Connecticut 6510
97/499 Geocoded: 1450 Chapel St, New Haven, Connecticut 6511
98/499 Geocoded: 4755 Ogletown-Stanton Rd, Newark, Delaware 19713
99/499 Geocoded: 1600 Rockland Rd, Wilmington, Delaware 19803
100/499 Geocoded: 900 23rd St, Washington, District of Columbia 20037
101/499 Geocoded: 2041 Georgia Ave, Washington, District of Columbia 20060
102/499 Geocoded: 615 N Bonita Ave, Panama City, Florida 32401
103/499 Geocoded: 1350 Hickory St, Melbourne, Florida 32901
104/499 Geocoded: 3501 Johnson St, Hollywood, Florida 33021
105/499 Geocoded: 1600 S Andrews Ave, Fort Lauderdale, Florida 33316
106/499 Geocoded: 201 E Sample Rd, Pompano Beach, Florida 33064
107/499 Geocoded: 2001 Kingsley Ave, Orange Park, Florida 32073
108/499 Geocoded: 655 W 8th St, Jacksonville, Florida 32209
109/499 Geocoded: 800 Prudential Dr, Jacksonville, Florida 32207
110/499 Geocoded: 1000 W Moreno St, Pensacola, Florida 32501
111/499 Geocoded: 5151 N Ninth Ave, Pensacola, Florida 32504
112/499 Geocoded: 3001 Martin Luther King Jr. Blvd, Tampa, Florida 33607
113/499 Geocoded: 2776 Cleveland Ave, Fort Myers, Florida 33901
114/499 Geocoded: 1300 Miccosukee Rd, Tallahassee, Florida 32308
115/499 Geocoded: 1431 SW 1st Ave, Ocala, Florida 34471
116/499 Geocoded: 3100 SW 62nd Ave, Miami, Florida 33155
117/499 Geocoded: 20900 Biscayne Blvd, Miami, Florida 33180
118/499 Geocoded: 9333 SW 152nd St, Palmetto Bay, Florida 33157
119/499 Geocoded: 1000 Mar-Walt Dr, Fort Walton Beach, Florida 32547
120/499 Geocoded: 700 W Oak St, Kissimmee, Florida 34741
121/499 Geocoded: 5352 Linton Blvd, Delray Beach, Florida 33484
122/499 Geocoded: 901 45th St, Mangonia Park, Florida 33407
123/499 Geocoded: 14000 Fivay Rd, Hudson, Florida 34667
124/499 Geocoded: 701 6th St South, St Petersburg, Florida 33701
125/499 Geocoded: 501 6th Ave South, St Petersburg, Florida 33701
126/499 Geocoded: 1324 Lakeland Hills Blvd, Lakeland, Florida 33805
127/499 Geocoded: 1700 S Tamiami Trail, Sarasota, Florida 34239
128/499 Geocoded: 1401 W Seminole Blvd, Sanford, Florida 32771
129/499 Geocoded: 1700 S 23rd St, Fort Pierce, Florida 34950
130/499 Geocoded: 303 N Clyde Morris Blvd, Daytona Beach, Florida 32114
131/499 Geocoded:  3625 University Blvd S, Jacksonville, Florida 32216
132/499 Geocoded: 1199 Prince Ave, Athens, Georgia 30606
133/499 Geocoded: 303 Parkway Drive Northeast, Atlanta, Georgia 30312
134/499 Geocoded: 1405 Clifton Rd, Atlanta, Georgia 30322
135/499 Geocoded: 1001 Johnson Ferry Rd, Atlanta, Georgia 30342
136/499 Geocoded: 1120 15th St, Augusta, Georgia 30912
137/499 Geocoded: 710 Center St, Columbus, Georgia 31904
138/499 Geocoded: 743 Spring St, Gainesville, Georgia 30501
139/499 Geocoded: 1000 Medical Center Blvd, Lawrenceville, Georgia 30046
140/499 Geocoded: 777 Hemlock St, Macon, Georgia 31201
141/499 Geocoded: 677 Church St, Marietta, Georgia 30060
142/499 Geocoded: 304 Turner McCall Blvd, Rome, Georgia 30165
143/499 Geocoded: 3000 Hospital Blvd, Roswell, Georgia 30076
144/499 Geocoded: 4700 Waters Ave, Savannah, Georgia 31404
145/499 Geocoded: 1301 Punchbowl St, Honolulu, Hawaii 96813
146/499 Geocoded: 1 Jarrett White Rd, Honolulu, Hawaii 96859
147/499 Geocoded: 1055 N Curtis Rd, Boise, Idaho 83706
148/499 Geocoded: 777 Hospital Way, Pocatello, Idaho 83201
149/499 Geocoded: 190 E Bannock St, Boise, Idaho 83712
150/499 Geocoded: 1005 Broadway St, Quincy, Illinois 62301
151/499 Geocoded: 611 W Park St, Urbana, Illinois 61801
152/499 Geocoded: 4440 W 95th St, Oak Lawn, Illinois 60453
153/499 Geocoded: 5101 Willow Springs Rd, La Grange, Illinois 60525
154/499 Geocoded: 701 West North Ave, Melrose Park, Illinois 60160
155/499 Geocoded: 3249 South Oak Park Ave, Berwyn, Illinois 60402
156/499 Geocoded: 1775 Dempster St, Park Ridge, Illinois 60068
157/499 Geocoded: 800 West Biesterfield Road, Elk Grove Village, Illinois 60007
158/499 Geocoded: 800 West Central Road, Arlington Heights, Illinois 60005
159/499 Geocoded: 1555 Barrington Road, Hoffman Estates, Illinois 60169
160/499 Geocoded: 2650 Ridge Avenue, Evanston, Illinois 60201
161/499 Geocoded: 2100 Pfingsten Road, Glenview, Illinois 60025
162/499 Geocoded: 355 Ridge Avenue, Evanston, Illinois 60202
163/499 Geocoded: 836 West Wellington Ave, Chicago, Illinois 60657
164/499 Geocoded: 225 East Chicago Avenue, Chicago, Illinois 60614
165/499 Geocoded: 1500 South Fairfield Ave, Chicago, Illinois 60608
166/499 Geocoded: 251 East Huron Street, Chicago, Illinois 60611
167/499 Geocoded: 701 Winthrop Ave, Glendale Heights, Illinois 60139
168/499 Geocoded: 120 North Oak St, Hinsdale, Illinois 60521
169/499 Geocoded: 3815 Highland Ave, Downers Grove, Illinois 60515
170/499 Geocoded: 25 N Winfield Rd, Winfield, Illinois 60190
171/499 Geocoded: 801 S Washington St, Naperville, Illinois 60540
172/499 Geocoded: 155 East Brush Hill Rd, Elmhurst, Illinois 60126
173/499 Geocoded: 405 W Jackson St, Carbondale, Illinois 62901
174/499 Geocoded: 500 W Court St, Kankakee, Illinois 60901
175/499 Geocoded: 350 N Wall Street, Kankakee, Illinois 60901
176/499 Geocoded: 1425 North Randall Rd, Elgin, Illinois 60120
177/499 Geocoded: 300 Randall Road, Geneva, Illinois 60134
178/499 Geocoded: 1325 North Highland Ave, Aurora, Illinois 60506
179/499 Geocoded: 77 North Airlite Street, Elgin, Illinois 60120
180/499 Geocoded: 2000 Ogden Avenue, Aurora, Illinois 60504
181/499 Geocoded: 450 West Highway 22, Barrington, Illinois 60010
182/499 Geocoded: 801 South Milwaukee Ave, Libertyville, Illinois 60048
183/499 Geocoded: 777 Park Avenue West, Highland Park, Illinois 60035
184/499 Geocoded: 1000 N Westmoreland Rd, Lake Forest, Illinois 60045
185/499 Geocoded: 1324 North Sheridan Road, Waukegan, Illinois 60085
186/499 Geocoded: 2300 N Edward St, Decatur, Illinois 62526
187/499 Geocoded: 150 West High St, Morris, Illinois 60450
188/499 Geocoded: 10400 Haligus Road, Huntley, Illinois 60142
189/499 Geocoded: 4201 Medical Center Drive, McHenry, Illinois 60050
190/499 Geocoded: 1304 Franklin Ave, Normal, Illinois 61761
191/499 Geocoded: 2200 E Washington St, Bloomington, Illinois 61701
192/499 Geocoded: 530 NE Glen Oak Ave, Peoria, Illinois 61637
193/499 Geocoded: 221 NE Glen Oak Ave, Peoria, Illinois 61636
194/499 Geocoded: 801 Illini Dr, Silvis, Illinois 61282
195/499 Geocoded: 2701 17th St, Rock Island, Illinois 61201
196/499 Geocoded: 800 E Carpenter St, Springfield, Illinois 62769
197/499 Geocoded: 333 North Madison St, Joliet, Illinois 60435
198/499 Geocoded: 1900 Silver Cross Blvd, New Lenox, Illinois 60451
199/499 Geocoded: 500 Remington Blvd, Bolingbrook, Illinois 60440
200/499 Geocoded: 8201 E Riverside Blvd, Rockford, Illinois 61114
201/499 Geocoded: 1401 E State St, Rockford, Illinois 61104
202/499 Geocoded: 11109 Parkview Plaza Dr, Fort Wayne, Indiana 46845
203/499 Geocoded: 1701 N Senate, Indianapolis, Indiana 46206
204/499 Geocoded: 615 N Michigan St, South Bend, Indiana 46601
205/499 Geocoded: 3700 Washington Ave, Evansville, Indiana 47714
206/499 Geocoded: 600 Mary St, Evansville, Indiana 47747
207/499 Geocoded: 1200 Pleasant St, Des Moines, Iowa 50309
208/499 Geocoded: 1111 6th Ave, Des Moines, Iowa 50314
209/499 Geocoded: 801 5th St, Sioux City, Iowa 51101
210/499 Geocoded: 10500 Quivira Rd, Overland Park, Kansas 66215
211/499 Geocoded: 550 N Hillside, Wichita, Kansas 67214
212/499 Geocoded: 1500 SW 10th Ave, Topeka, Kansas 66604
213/499 Geocoded: 800 Rose St, Lexington, Kentucky 40536
214/499 Geocoded: 231 East Chestnut St, Louisville, Kentucky 40202
215/499 Geocoded: 911 Bypass Rd, Pikeville, Kentucky 41501
216/499 Geocoded: 5000 Hennessy Blvd, Baton Rouge, Louisiana 70808
217/499 Geocoded: 1214 Coolidge Blvd, Lafayette, Louisiana 70503
218/499 Geocoded: 211 Fourth St, Alexandria, Louisiana 71301
219/499 Geocoded: 95 Judge Tanner Blvd, Covington, Louisiana 70433
220/499 Geocoded: 15790 Paul Vega MD Dr, Hammond, Louisiana 70403
221/499 Geocoded: 489 State St, Bangor, Maine 4401
222/499 Geocoded: 2401 W Belvedere Ave, Baltimore, Maryland 21215
223/499 Geocoded: 8901 Rockville Pike, Bethesda, Maryland 20889
224/499 Geocoded: 8600 Old Georgetown Rd, Bethesda, Maryland 20814
225/499 Geocoded: 3001 Hospital Drive, Cheverly, Maryland 20785
226/499 Geocoded: 101 Page St, New Bedford, Massachusetts 2740
227/499 Geocoded: 759 Chestnut St, Springfield, Massachusetts 1199
228/499 Geocoded: 41 Mall Rd, Burlington, Massachusetts 1805
229/499 Geocoded: 55 Fogg Rd, South Weymouth, Massachusetts 2190
230/499 Geocoded: 330 Brookline Ave, Boston, Massachusetts 2215
231/499 Geocoded: 300 Longwood Ave, Boston, Massachusetts 2115
232/499 Geocoded: 1 Boston Medical Center Pl, Boston, Massachusetts 2118
233/499 Geocoded: 800 Washington St, Boston, Massachusetts 2111
234/499 Geocoded: 416 Connable Ave, Petoskey, Michigan 49770
235/499 Geocoded: 1 Genesys Pkwy, Grand Blanc, Michigan 48439
236/499 Geocoded: 1105 Sixth St, Traverse City, Michigan 49684
237/499 Geocoded: 1215 E Michigan Ave, Lansing, Michigan 48909
238/499 Geocoded: 205 N East Ave, Jackson, Michigan 49201
239/499 Geocoded: 1521 Gull Rd, Kalamazoo, Michigan 49048
240/499 Geocoded: 200 Jefferson Ave, Grand Rapids, Michigan 49503
241/499 Geocoded: 5900 Byron Center Rd, Wyoming, Michigan 49519
242/499 Geocoded: 1375 N Main St, Lapeer, Michigan 48446
243/499 Geocoded: 15855 Nineteen Mile Rd, Clinton Township, Michigan 48038
244/499 Geocoded: 1000 Harrington St, Mount Clemens, Michigan 48043
245/499 Geocoded: 580 W College Avenue , Marquette, Michigan 49855
246/499 Geocoded: 4000 Wellness Dr, Midland, Michigan 48670
247/499 Geocoded: 1700 Clinton St, Muskegon, Michigan 49444
248/499 Geocoded: 16001 W Nine Mile Rd, Southfield, Michigan 48075
249/499 Geocoded: 47601 Grand River Ave, Novi, Michigan 48374
250/499 Geocoded: 44201 Dequindre Rd, Troy, Michigan 48085
251/499 Geocoded: 3601 W 13 Mile Rd, Royal Oak, Michigan 48073
252/499 Geocoded: 28050 Grand River Ave, Farmington Hills, Michigan 48336
253/499 Geocoded: 50 N Perry St, Pontiac, Michigan 48342
254/499 Geocoded: 44405 Woodward Ave, Pontiac, Michigan 48341
255/499 Geocoded: 800 S Washington Ave, Saginaw , Michigan 48601
256/499 Geocoded: 1447 N Harrison, Saginaw , Michigan 48602
257/499 Geocoded: 5301 Mcauley Dr, Ypsilanti, Michigan 48197
258/499 Geocoded: 22101 Moross Rd, Detroit, Michigan 48236
259/499 Geocoded: 5450 Fort St, Trenton, Michigan 48183
260/499 Geocoded: 18101 Oakwood Blvd, Dearborn, Michigan 48124
261/499 Geocoded: 6071 West Outer Dr, Detroit, Michigan 48235
262/499 Geocoded: 2799 West Grand Blvd, Detroit, Michigan 48202
263/499 Geocoded: 36475 Five Mile Rd, Livonia, Michigan 48154
264/499 Geocoded: 4050 Coon Rapids Blvd, Coon Rapids, Minnesota  55433
265/499 Geocoded: 407 E 3rd St, Duluth, Minnesota  55805
266/499 Geocoded: 915 E 1st St, Duluth, Minnesota  55805
267/499 Geocoded: 2525 Chicago Ave South, Minneapolis, Minnesota  55404
268/499 Geocoded: 420 Delaware St SE, Minneapolis, Minnesota  55455
269/499 Geocoded: 3300 Oakdale Ave N, Robbinsdale, Minnesota  55422
270/499 Geocoded: 1216 2nd Street SW, Rochester, Minnesota  55902
271/499 Geocoded: 1406 Sixth Ave N, Saint Cloud, Minnesota  56303
272/499 Geocoded: 6051 US Highway 49, Hattiesburg, Mississippi 39401
273/499 Geocoded: 4500 13th Street, Gulfport, Mississippi 39501
274/499 Geocoded: 2500 North State St, Jackson, Mississippi 39216
275/499 Geocoded: 830 South Gloster St, Tupelo, Mississippi 38801
276/499 Geocoded: 5325 Faron St, Saint Joseph, Missouri 64506
277/499 Geocoded: 2525 Glenn Hendren Dr, Liberty, Missouri 64068
278/499 Geocoded: 2800 Clay Edwards Dr, North Kansas City, Missouri 64116
279/499 Geocoded: 3801 S National Ave, Springfield, Missouri 65807
280/499 Geocoded: 2301 Holmes St, Kansas City, Missouri 64108
281/499 Geocoded: 4401 Wornall Rd, Kansas City, Missouri 64111
282/499 Geocoded: 19600 East 39th St, Independence , Missouri 64057
283/499 Geocoded: 1102 W 32nd St, Joplin, Missouri 64804
284/499 Geocoded: 100 Mercy Way, Joplin, Missouri 64804
285/499 Geocoded: 12303 DePaul Dr, Bridgeton, Missouri 63044
286/499 Geocoded: 10010 Kennerly Rd, Saint Louis, Missouri 63128
287/499 Geocoded: 3635 Vista Ave, Saint Louis, Missouri 63104
288/499 Geocoded: 1465 S Grand Blvd, Saint Louis, Missouri 63104
289/499 Geocoded: 1101 26th St S, Great Falls, Montana 59405
290/499 Geocoded: 500 W Broadway, Missoula, Montana 59802
291/499 Geocoded: 2800 10th Ave North, Billings, Montana 59108
292/499 Geocoded: 1233 N 30th St, Billings, Montana 59101
293/499 Geocoded: 10 E 31st St, Kearney , Nebraska 68847
294/499 Geocoded: 7500 Mercy Rd, Omaha, Nebraska 68124
295/499 Geocoded: 8200 Dodge St, Omaha, Nebraska 68114
296/499 Geocoded: 4350 Dewey Ave, Omaha, Nebraska 68105
297/499 Geocoded: 2300 South 16th St, Lincoln, Nebraska 68502
298/499 Geocoded: 4021 Avenue B, Scottsbluff, Nebraska 69361
299/499 Geocoded: 1155 Mill St, Reno, Nevada 89502
300/499 Geocoded: 1 Medical Center Dr, Lebanon, New Hampshire 3756
301/499 Geocoded: 250 Pleasant St, Concord, New Hampshire 3301
302/499 Geocoded: 1 Elliot Way, Manchester, New Hampshire 3103
303/499 Geocoded: 333 Borthwick Ave, Portsmouth, New Hampshire 3801
304/499 Geocoded: 1925 Pacific Ave, Atlantic City, New Jersey 8401
305/499 Geocoded: 30 Prospect Ave, Hackensack, New Jersey 7601
306/499 Geocoded: 1 Cooper Plaza, Camden, New Jersey 8103
307/499 Geocoded: 150 Bergen St, Newark, New Jersey 7103
308/499 Geocoded: 355 Grand St, Jersey City, New Jersey 7302
309/499 Geocoded: 750 Brunswick Ave, Trenton, New Jersey 8638
310/499 Geocoded: 1 Robert Wood Johnson Pl, New Brunswick, New Jersey 8901
311/499 Geocoded: 1945 Route 33, Neptune, New Jersey 7754
312/499 Geocoded: 100 Madison Ave, Morristown, New Jersey 7960
313/499 Geocoded: 703 Main St, Paterson, New Jersey 7503
314/499 Geocoded: 43 New Scotland Ave, Albany, New York 12208
315/499 Geocoded: 234 E 149th St, Bronx, New York 10451

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE,FULL_ADDRESS,Latitude,Longitude
0,Alaska,AK,Anchorage,4315 Diplomacy Dr,Anchorage,99508,6940010.0,Alaska Native Medical Center,173,NaN,...,1.0,0.0,1.0,NaN,Yes,NaN,(907) 563-2662,"4315 Diplomacy Dr, Anchorage, Alaska 99508",61.182772,-149.800177
1,Alaska,AK,Anchorage,3200 Providence Dr,Anchorage,99508,6940020.0,Providence Alaska Medical Center/Children's Ho...,401,NaN,...,1.0,0.0,1.0,NaN,Yes,NaN,(907) 562-2211,"3200 Providence Dr, Anchorage, Alaska 99508",61.187168,-149.819439
2,Alabama,AL,Houston,1108 Ross Clark Cir,Dothan,36301,6530373.0,Southeast Alabama Medical Center,387,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(334) 793-8111,"1108 Ross Clark Cir, Dothan, Alabama 36301",31.214885,-85.361261
5,Alabama,AL,Madison,101 Sivley Rd,Huntsville,35801,6530510.0,Huntsville Hospital,958,NaN,...,0.0,0.0,0.0,NaN,Yes,NaN,(256) 265-1000,"101 Sivley Rd, Huntsville, Alabama 35801",34.720467,-86.580963
7,Alabama,AL,Montgomery,2105 E South Blvd,Montgomery,36116,6530705.0,Baptist Medical Center South,492,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(334) 288-2100,"2105 E South Blvd, Montgomery, Alabama 36116",32.327953,-86.277782

In [72]:
import time
import numpy as np
from geopy.geocoders import Nominatim

# Re-initialize geolocator with an even longer timeout (e.g., 10 seconds)
geolocator = Nominatim(user_agent="non_burn_center_locator", timeout=10)

#df_non_burn_center
# Identify rows that still have nulls in Latitude or Longitude
null_coords_mask = df_non_burn_center['Latitude'].isnull() | df_non_burn_center['Longitude'].isnull()
df_needs_geocoding = df_non_burn_center[null_coords_mask].copy()

# Create new lists to store geocoded results for these specific rows
new_latitudes = []
new_longitudes = []

for index, row in df_needs_geocoding.iterrows():
    address = row['FULL_ADDRESS']
    try:
        location = geolocator.geocode(address)
        if location:
            new_latitudes.append(location.latitude)
            new_longitudes.append(location.longitude)
        else:
            new_latitudes.append(np.nan)  # Use np.nan instead of None
            new_longitudes.append(np.nan) # Use np.nan instead of None
    except Exception as e:
        print(f"Error geocoding {address}: {e}")
        new_latitudes.append(np.nan)  # Use np.nan instead of None
        new_longitudes.append(np.nan) # Use np.nan instead of None
    time.sleep(2) # Keep the 2-second delay to respect usage policy

# Update the original df_burn_center with the new coordinates
# Ensure the lengths match before assignment
if len(new_latitudes) == len(df_needs_geocoding):
    df_non_burn_center.loc[null_coords_mask, 'Latitude'] = new_latitudes
    df_non_burn_center.loc[null_coords_mask, 'Longitude'] = new_longitudes
else:
    print("Mismatch in length, cannot update directly. Review individual geocoding.")


print(f"Nulls in Latitude after re-attempt: {df_non_burn_center['Latitude'].isnull().sum()}")
print(f"Nulls in Longitude after re-attempt: {df_non_burn_center['Longitude'].isnull().sum()}")
df_non_burn_center.head()

Nulls in Latitude after re-attempt: 42
Nulls in Longitude after re-attempt: 42

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE,FULL_ADDRESS,Latitude,Longitude
0,Alaska,AK,Anchorage,4315 Diplomacy Dr,Anchorage,99508,6940010.0,Alaska Native Medical Center,173,NaN,...,1.0,0.0,1.0,NaN,Yes,NaN,(907) 563-2662,"4315 Diplomacy Dr, Anchorage, Alaska 99508",61.182772,-149.800177
1,Alaska,AK,Anchorage,3200 Providence Dr,Anchorage,99508,6940020.0,Providence Alaska Medical Center/Children's Ho...,401,NaN,...,1.0,0.0,1.0,NaN,Yes,NaN,(907) 562-2211,"3200 Providence Dr, Anchorage, Alaska 99508",61.187168,-149.819439
2,Alabama,AL,Houston,1108 Ross Clark Cir,Dothan,36301,6530373.0,Southeast Alabama Medical Center,387,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(334) 793-8111,"1108 Ross Clark Cir, Dothan, Alabama 36301",31.214885,-85.361261
5,Alabama,AL,Madison,101 Sivley Rd,Huntsville,35801,6530510.0,Huntsville Hospital,958,NaN,...,0.0,0.0,0.0,NaN,Yes,NaN,(256) 265-1000,"101 Sivley Rd, Huntsville, Alabama 35801",34.720467,-86.580963
7,Alabama,AL,Montgomery,2105 E South Blvd,Montgomery,36116,6530705.0,Baptist Medical Center South,492,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(334) 288-2100,"2105 E South Blvd, Montgomery, Alabama 36116",32.327953,-86.277782

Dropping non-burn centers that could not be geocoded

In [73]:
df_non_burn_center.dropna(subset=['Latitude', 'Longitude'], inplace=True)
print(f"Number of non burn centers after dropping un-geocoded: {len(df_burn_center)}")
print(f"Nulls in Latitude after cleanup: {df_non_burn_center['Latitude'].isnull().sum()}")
print(f"Nulls in Longitude after cleanup: {df_non_burn_center['Longitude'].isnull().sum()}")
df_non_burn_center.head()

Number of non burn centers after dropping un-geocoded: 131
Nulls in Latitude after cleanup: 0
Nulls in Longitude after cleanup: 0

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE,FULL_ADDRESS,Latitude,Longitude
0,Alaska,AK,Anchorage,4315 Diplomacy Dr,Anchorage,99508,6940010.0,Alaska Native Medical Center,173,NaN,...,1.0,0.0,1.0,NaN,Yes,NaN,(907) 563-2662,"4315 Diplomacy Dr, Anchorage, Alaska 99508",61.182772,-149.800177
1,Alaska,AK,Anchorage,3200 Providence Dr,Anchorage,99508,6940020.0,Providence Alaska Medical Center/Children's Ho...,401,NaN,...,1.0,0.0,1.0,NaN,Yes,NaN,(907) 562-2211,"3200 Providence Dr, Anchorage, Alaska 99508",61.187168,-149.819439
2,Alabama,AL,Houston,1108 Ross Clark Cir,Dothan,36301,6530373.0,Southeast Alabama Medical Center,387,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(334) 793-8111,"1108 Ross Clark Cir, Dothan, Alabama 36301",31.214885,-85.361261
5,Alabama,AL,Madison,101 Sivley Rd,Huntsville,35801,6530510.0,Huntsville Hospital,958,NaN,...,0.0,0.0,0.0,NaN,Yes,NaN,(256) 265-1000,"101 Sivley Rd, Huntsville, Alabama 35801",34.720467,-86.580963
7,Alabama,AL,Montgomery,2105 E South Blvd,Montgomery,36116,6530705.0,Baptist Medical Center South,492,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(334) 288-2100,"2105 E South Blvd, Montgomery, Alabama 36116",32.327953,-86.277782

# Mapping out the address

In [74]:
pip install folium

Defaulting to user installation because normal site-packages is not writeable
Collecting folium
  Downloading folium-0.20.0-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting branca>=0.6.0 (from folium)
  Downloading branca-0.8.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: jinja2>=2.9 in c:\users\arthu\appdata\roaming\python\python313\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\users\arthu\appdata\roaming\python\python313\site-packages (from folium) (2.2.6)
Requirement already satisfied: requests in c:\users\arthu\appdata\roaming\python\python313\site-packages (from folium) (2.32.5)
Collecting xyzservices (from folium)
  Downloading xyzservices-2025.11.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\arthu\appdata\roaming\python\python313\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\arthu\appdata\roaming\python\python313\site-packages (from requests->folium) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\arthu\appdata\roaming\python\python313\site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\arthu\appdata\roaming\python\python313\site-packages (from requests->folium) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arthu\appdata\roaming\python\python313\site-packages (from requests->folium) (2025.8.3)
Downloading folium-0.20.0-py2.py3-none-any.whl (113 kB)
Downloading branca-0.8.2-py3-none-any.whl (26 kB)
Downloading xyzservices-2025.11.0-py3-none-any.whl (93 kB)
Installing collected packages: xyzservices, branca, folium

   ------------- -------------------------- 1/3 [branca]
   -------------------------- ------------- 2/3 [folium]
   -------------------------- ------------- 2/3 [folium]
   -------------------------- ------------- 2/3 [folium]
   -------------------------- ------------- 2/3 [folium]
   ---------------------------------------- 3/3 [folium]

Successfully installed branca-0.8.2 folium-0.20.0 xyzservices-2025.11.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [75]:
import folium

# Initialize a Folium map centered around the average coordinates of the burn centers
# Using a default location if df_burn_center is empty or has no coordinates
if not df_burn_center.empty and 'Latitude' in df_burn_center.columns and 'Longitude' in df_burn_center.columns:
    map_center = [df_burn_center['Latitude'].mean(), df_burn_center['Longitude'].mean()]
else:
    map_center = [39.8283, -98.5795] # Geographic center of the contiguous United States

m = folium.Map(location=map_center, zoom_start=4)
print("Folium map initialized.")

Folium map initialized.

In [76]:
for index, row in df_burn_center.iterrows():
    # Create popup content with relevant information
    popup_content = f"<b>Hospital:</b> {row['HOSPITAL_NAME']}<br>"
    popup_content += f"<b>Address:</b> {row['FULL_ADDRESS']}<br>"
    popup_content += f"<b>Burn Beds:</b> {row['BURN_BEDS'] if pd.notna(row['BURN_BEDS']) else 'N/A'}<br>"
    popup_content += f"<b>ACS Verified:</b> {row['ACS_VERIFIED']}<br>"
    popup_content += f"<b>ABA Verified:</b> {row['ABA_VERIFIED']}"

    # Add marker to the map
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=folium.Popup(popup_content, max_width=300),
        tooltip=row['HOSPITAL_NAME'] # Tooltip on hover
    ).add_to(m)

# Display the map
m

# Marking the distance
In this section we are going to go through levels of marking the various distances between burn centers and non burn centers. The various distances will determine the degree experts and resources can be shared. It also determines the kind of transportation that can be used and if non resources apart from digital ones can be shared.

## Calculate Distances and Identify Nearby Non-Burn Centers

### Subtask:
For each non-burn center, calculate its distance to every burn center using their latitude and longitude coordinates. Then, identify and filter the non-burn centers that are within a 20-mile radius of at least one burn center. This will involve using the `geopy.distance` module to perform accurate distance calculations.

**Reasoning**:
The subtask requires calculating distances between non-burn centers and burn centers, then filtering for those within a 20-mile radius. To do this efficiently, I need to import the `geodesic` function from `geopy.distance`.

In [77]:
from geopy.distance import geodesic

print("geodesic imported successfully.")

geodesic imported successfully.

**Reasoning**:
As instructed by the subtask, I will now iterate through each non-burn center, calculate its distance to every burn center, and store the non-burn centers that are within a 20-mile radius in a new DataFrame, using the previously imported `geodesic` function.

In [78]:
nearby_non_burn_centers_list = []

for index_non_burn, row_non_burn in df_non_burn_center.iterrows():
    non_burn_center_coords = (row_non_burn['Latitude'], row_non_burn['Longitude'])
    found_nearby = False
    for index_burn, row_burn in df_burn_center.iterrows():
        burn_center_coords = (row_burn['Latitude'], row_burn['Longitude'])

        # Ensure both coordinates are not None/NaN before calculating distance
        if pd.notna(non_burn_center_coords[0]) and pd.notna(non_burn_center_coords[1]) and \
           pd.notna(burn_center_coords[0]) and pd.notna(burn_center_coords[1]):
            distance_miles = geodesic(non_burn_center_coords, burn_center_coords).miles

            if distance_miles <= 20:
                nearby_non_burn_centers_list.append(row_non_burn)
                found_nearby = True
                break  # Found a nearby burn center, move to the next non-burn center

# Convert the list of Series (rows) into a DataFrame
df_nearby_non_burn_centers = pd.DataFrame(nearby_non_burn_centers_list)

print(f"Number of non-burn centers within 20 miles of a burn center: {len(df_nearby_non_burn_centers)}")
df_nearby_non_burn_centers.head()

Number of non-burn centers within 20 miles of a burn center: 222

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE,FULL_ADDRESS,Latitude,Longitude
9,Arizona,AZ,Maricopa,1955 W Frye Rd,Chandler,85224,6860028.0,Chandler Regional Medical Center,338,NaN,...,0.0,0.0,0.0,NaN,Yes,NaN,(480) 728-3000,"1955 W Frye Rd, Chandler, Arizona 85224",33.296848,-111.874084
10,Arizona,AZ,Maricopa,5555 W Thunderbird Rd,Glendale,85306,6860013.0,Banner Thunderbird Medical Center,595,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(602) 865-5555,"5555 W Thunderbird Rd, Glendale, Arizona 85306",33.608948,-112.179739
11,Arizona,AZ,Maricopa,13677 W McDowell Rd,Goodyear,85395,6860027.0,Abrazo West Campus,188,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(623) 882-1500,"13677 W McDowell Rd, Goodyear, Arizona 85395",33.461962,-112.352849
12,Arizona,AZ,Maricopa,1400 S Dobson Rd,Mesa,85202,6860016.0,Banner Desert Medical Center/Banner Children's...,605,NaN,...,1.0,0.0,1.0,NaN,Yes,NaN,(480) 412-3000,"1400 S Dobson Rd, Mesa, Arizona 85202",33.390213,-111.878137
13,Arizona,AZ,Maricopa,1111 E McDowell Rd,Phoenix,85006,6860250.0,Banner University Medical Center - Phoenix,698,NaN,...,0.0,0.0,0.0,NaN,Yes,NaN,(602) 239-2000,"1111 E McDowell Rd, Phoenix, Arizona 85006",33.465264,-112.056475

**Reasoning**:
With the nearby non-burn centers identified, the next step is to initialize a `folium` map centered on the average coordinates of all burn centers, and then add markers and circles as required for visualization.

In [79]:
import folium

# Initialize a Folium map centered around the average coordinates of the burn centers
# Using a default location if df_burn_center is empty or has no coordinates
if not df_burn_center.empty and 'Latitude' in df_burn_center.columns and 'Longitude' in df_burn_center.columns:
    map_center = [df_burn_center['Latitude'].mean(), df_burn_center['Longitude'].mean()]
else:
    map_center = [39.8283, -98.5795] # Geographic center of the contiguous United States

m = folium.Map(location=map_center, zoom_start=4)
print("Folium map initialized.")

Folium map initialized.

**Reasoning**:
Now that the Folium map is initialized, I will add markers for each burn center along with a 20-mile radius circle, and then add distinct markers for the identified nearby non-burn centers, as per the subtask's requirements for visualization. Finally, the map will be displayed.

In [80]:
for index, row in df_burn_center.iterrows():
    # Create popup content for burn centers
    popup_content = f"<b>Burn Center:</b> {row['HOSPITAL_NAME']}<br>"
    popup_content += f"<b>Address:</b> {row['FULL_ADDRESS']}<br>"
    popup_content += f"<b>Burn Beds:</b> {row['BURN_BEDS'] if pd.notna(row['BURN_BEDS']) else 'N/A'}<br>"
    popup_content += f"<b>ACS Verified:</b> {row['ACS_VERIFIED']}<br>"
    popup_content += f"<b>ABA Verified:</b> {row['ABA_VERIFIED']}"

    # Add marker for burn center
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=folium.Popup(popup_content, max_width=300),
        tooltip=row['HOSPITAL_NAME'],
        icon=folium.Icon(color='red', icon='fire', prefix='fa') # Distinct icon for burn centers
    ).add_to(m)

    # Add a 20-mile radius circle around burn centers (1 mile = 1609.34 meters)
    folium.Circle(
        location=[row['Latitude'], row['Longitude']],
        radius=20 * 1609.34, # Radius in meters
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity=0.1
    ).add_to(m)


for index, row in df_nearby_non_burn_centers.iterrows():
    # Create popup content for nearby non-burn centers
    popup_content = f"<b>Non-Burn Center:</b> {row['HOSPITAL_NAME']}<br>"
    popup_content += f"<b>Address:</b> {row['FULL_ADDRESS']}"

    # Add marker for nearby non-burn center with a different color
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=folium.Popup(popup_content, max_width=300),
        tooltip=row['HOSPITAL_NAME'],
        icon=folium.Icon(color='blue', icon='hospital', prefix='fa') # Distinct icon for non-burn centers
    ).add_to(m)

# Display the map
m

## Final Task

### Subtask:
Provide a summary of the analysis, including the number of non-burn centers identified within the 20-mile radius, and display the interactive Folium map.

## Summary:

### Q&A
*   **Number of non-burn centers identified within the 20-mile radius:** A total of 222 non-burn centers were identified within a 20-mile radius of at least one burn center.
*   **Interactive Folium map:** The interactive Folium map was successfully generated and displayed, showing burn centers with their 20-mile radius circles and distinct markers for nearby non-burn centers.

### Data Analysis Key Findings
*   The `geodesic` function from the `geopy.distance` module was successfully used to calculate distances between non-burn centers and burn centers.
*   222 non-burn centers were identified as being within a 20-mile radius of at least one burn center. These centers were compiled into a new DataFrame, `df_nearby_non_burn_centers`.
*   An interactive Folium map was initialized, centered on the average coordinates of the burn centers, to visualize the locations.
*   Burn centers were marked with distinct red icons and had a 20-mile radius circle overlay.
*   The identified nearby non-burn centers were marked with distinct blue icons on the map, allowing for clear visual differentiation.
*   Both burn center and non-burn center markers included pop-ups with relevant information such as hospital name and address.

### Insights or Next Steps
*   The presence of 222 non-burn centers within a 20-mile radius of specialized burn centers highlights potential for efficient patient transfer, collaborative care, or post-acute care coordination.
*   A valuable next step would be to analyze the types of services offered by these nearby non-burn centers to determine their capacity for initial stabilization or follow-up care for burn patients, optimizing resource allocation and patient pathways.

## Calculate Distances and Identify Nearby Non-Burn Centers (30-150 miles)

### Subtask:
For each non-burn center, calculate its distance to every burn center. Identify and filter non-burn centers that are within a distance range of 30 to 150 miles from at least one burn center, using the `geopy.distance` module.

**Reasoning**:
I need to calculate the distance between each non-burn center and all burn centers, then filter for those non-burn centers that fall within the 30 to 150-mile range as specified in the subtask. I will iterate through the dataframes, calculate distances, and store the relevant non-burn centers.

In [81]:
non_burn_centers_30_150_miles_list = []

for index_non_burn, row_non_burn in df_non_burn_center.iterrows():
    non_burn_center_coords = (row_non_burn['Latitude'], row_non_burn['Longitude'])
    found_in_range = False
    for index_burn, row_burn in df_burn_center.iterrows():
        burn_center_coords = (row_burn['Latitude'], row_burn['Longitude'])

        # Ensure both coordinates are not None/NaN before calculating distance
        if pd.notna(non_burn_center_coords[0]) and pd.notna(non_burn_center_coords[1]) and \
           pd.notna(burn_center_coords[0]) and pd.notna(burn_center_coords[1]):
            distance_miles = geodesic(non_burn_center_coords, burn_center_coords).miles

            if 30 <= distance_miles <= 150:
                non_burn_centers_30_150_miles_list.append(row_non_burn)
                found_in_range = True
                break  # Found a burn center within range, move to the next non-burn center

# Convert the list of Series (rows) into a DataFrame
df_non_burn_centers_30_150_miles = pd.DataFrame(non_burn_centers_30_150_miles_list)

print(f"Number of non-burn centers within 30-150 miles of a burn center: {len(df_non_burn_centers_30_150_miles)}")
df_non_burn_centers_30_150_miles.head()

Number of non-burn centers within 30-150 miles of a burn center: 406

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE,FULL_ADDRESS,Latitude,Longitude
5,Alabama,AL,Madison,101 Sivley Rd,Huntsville,35801,6530510.0,Huntsville Hospital,958,NaN,...,0.0,0.0,0.0,NaN,Yes,NaN,(256) 265-1000,"101 Sivley Rd, Huntsville, Alabama 35801",34.720467,-86.580963
7,Alabama,AL,Montgomery,2105 E South Blvd,Montgomery,36116,6530705.0,Baptist Medical Center South,492,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(334) 288-2100,"2105 E South Blvd, Montgomery, Alabama 36116",32.327953,-86.277782
8,Arizona,AZ,Coconino,1200 N Beaver St,Flagstaff,86001,6860021.0,Flagstaff Medical Center,268,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(928) 779-3366,"1200 N Beaver St, Flagstaff, Arizona 86001",35.208790,-111.644022
9,Arizona,AZ,Maricopa,1955 W Frye Rd,Chandler,85224,6860028.0,Chandler Regional Medical Center,338,NaN,...,0.0,0.0,0.0,NaN,Yes,NaN,(480) 728-3000,"1955 W Frye Rd, Chandler, Arizona 85224",33.296848,-111.874084
10,Arizona,AZ,Maricopa,5555 W Thunderbird Rd,Glendale,85306,6860013.0,Banner Thunderbird Medical Center,595,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(602) 865-5555,"5555 W Thunderbird Rd, Glendale, Arizona 85306",33.608948,-112.179739

**Reasoning**:
Now that `df_non_burn_centers_30_150_miles` has been created, I will initialize a new `folium` map. This will serve as the base for visualizing both the burn centers and the non-burn centers within the 30-150 mile range, ensuring a clean map for this specific visualization.

In [82]:
import folium

# Initialize a Folium map centered around the average coordinates of the burn centers
# Using a default location if df_burn_center is empty or has no coordinates
if not df_burn_center.empty and 'Latitude' in df_burn_center.columns and 'Longitude' in df_burn_center.columns:
    map_center = [df_burn_center['Latitude'].mean(), df_burn_center['Longitude'].mean()]
else:
    map_center = [39.8283, -98.5795] # Geographic center of the contiguous United States

m_30_150 = folium.Map(location=map_center, zoom_start=4)
print("Folium map initialized for 30-150 mile range visualization.")

Folium map initialized for 30-150 mile range visualization.

**Reasoning**:
Now that the Folium map `m_30_150` is initialized, I will add markers for each burn center along with a 20-mile radius circle, and then add distinct markers for the identified non-burn centers within the 30-150 mile range, as per the subtask's requirements for visualization. Finally, the map will be displayed.

In [83]:
for index, row in df_burn_center.iterrows():
    # Create popup content for burn centers
    popup_content = f"<b>Burn Center:</b> {row['HOSPITAL_NAME']}<br>"
    popup_content += f"<b>Address:</b> {row['FULL_ADDRESS']}<br>"
    popup_content += f"<b>Burn Beds:</b> {row['BURN_BEDS'] if pd.notna(row['BURN_BEDS']) else 'N/A'}<br>"
    popup_content += f"<b>ACS Verified:</b> {row['ACS_VERIFIED']}<br>"
    popup_content += f"<b>ABA Verified:</b> {row['ABA_VERIFIED']}"

    # Add marker for burn center
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=folium.Popup(popup_content, max_width=300),
        tooltip=row['HOSPITAL_NAME'],
        icon=folium.Icon(color='red', icon='fire', prefix='fa') # Distinct icon for burn centers
    ).add_to(m_30_150)

    # Add a 20-mile radius circle around burn centers (1 mile = 1609.34 meters)
    folium.Circle(
        location=[row['Latitude'], row['Longitude']],
        radius=20 * 1609.34, # Radius in meters
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity=0.1
    ).add_to(m_30_150)


for index, row in df_non_burn_centers_30_150_miles.iterrows():
    # Create popup content for non-burn centers in the 30-150 mile range
    popup_content = f"<b>Non-Burn Center (30-150 mi):</b> {row['HOSPITAL_NAME']}<br>"
    popup_content += f"<b>Address:</b> {row['FULL_ADDRESS']}"

    # Add marker for nearby non-burn center with a different color
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=folium.Popup(popup_content, max_width=300),
        tooltip=row['HOSPITAL_NAME'],
        icon=folium.Icon(color='blue', icon='hospital', prefix='fa') # Distinct icon for non-burn centers
    ).add_to(m_30_150)

# Display the map
m_30_150

## Final Task

### Subtask:
Provide a summary of the analysis, including the count of non-burn centers identified within the 30-150 mile range, and display the interactive Folium map.

## Summary:

### Q&A
*   How many non-burn centers were identified within the 30-150 mile range of a burn center?
    *   A total of 406 non-burn centers were identified within the 30-150 mile range of at least one burn center.
*   Was the interactive Folium map displayed?
    *   Yes, an interactive Folium map was successfully generated and displayed, visualizing both burn centers and the identified non-burn centers within the 30-150 mile range.

### Data Analysis Key Findings
*   The process successfully identified 406 non-burn centers located within a distance of 30 to 150 miles from at least one burn center.
*   An interactive Folium map was created to visualize these locations, clearly distinguishing burn centers (red markers with a 20-mile red radius circle) from the identified non-burn centers (blue markers).

### Insights or Next Steps
*   The large number of non-burn centers within the 30-150 mile range suggests potential opportunities for collaboration or referral networks to improve access to burn care in areas that are not immediately adjacent to a specialized burn center.
*   A subsequent step could involve analyzing the services and facilities available at these 406 identified non-burn centers to assess their capability to provide initial care, stabilization, or even intermediate burn treatment.

## Calculate distances that is above 150 miles

In [84]:
non_burn_centers_150_miles_plus_list = []

for index_non_burn, row_non_burn in df_non_burn_center.iterrows():
    non_burn_center_coords = (row_non_burn['Latitude'], row_non_burn['Longitude'])
    found_in_range = False
    for index_burn, row_burn in df_burn_center.iterrows():
        burn_center_coords = (row_burn['Latitude'], row_burn['Longitude'])

        # Ensure both coordinates are not None/NaN before calculating distance
        if pd.notna(non_burn_center_coords[0]) and pd.notna(non_burn_center_coords[1]) and \
           pd.notna(burn_center_coords[0]) and pd.notna(burn_center_coords[1]):
            distance_miles = geodesic(non_burn_center_coords, burn_center_coords).miles

            if  distance_miles > 150:
                non_burn_centers_150_miles_plus_list.append(row_non_burn)
                found_in_range = True
                break  # Found a burn center within range, move to the next non-burn center

# Convert the list of Series (rows) into a DataFrame
non_burn_centers_150_miles_plus= pd.DataFrame(non_burn_centers_150_miles_plus_list)

print(f"Number of non-burn centers within 30-150 miles of a burn center: {len(non_burn_centers_150_miles_plus)}")
non_burn_centers_150_miles_plus.head()

Number of non-burn centers within 30-150 miles of a burn center: 457

,STATE_FULL,STATE,COUNTY,ADDRESS,CITY,ZIP_CODE,AHA_ID,HOSPITAL_NAME,TOTAL_BEDS,BURN_BEDS,...,ADULT_TRAUMA_L2,PEDS_TRAUMA_L1,PEDS_TRAUMA_L2,ABA_VERIFIED,TC_STATE_DESIGNATED,BC_STATE_DESIGNATED,PHONE,FULL_ADDRESS,Latitude,Longitude
0,Alaska,AK,Anchorage,4315 Diplomacy Dr,Anchorage,99508,6940010.0,Alaska Native Medical Center,173,NaN,...,1.0,0.0,1.0,NaN,Yes,NaN,(907) 563-2662,"4315 Diplomacy Dr, Anchorage, Alaska 99508",61.182772,-149.800177
1,Alaska,AK,Anchorage,3200 Providence Dr,Anchorage,99508,6940020.0,Providence Alaska Medical Center/Children's Ho...,401,NaN,...,1.0,0.0,1.0,NaN,Yes,NaN,(907) 562-2211,"3200 Providence Dr, Anchorage, Alaska 99508",61.187168,-149.819439
2,Alabama,AL,Houston,1108 Ross Clark Cir,Dothan,36301,6530373.0,Southeast Alabama Medical Center,387,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(334) 793-8111,"1108 Ross Clark Cir, Dothan, Alabama 36301",31.214885,-85.361261
5,Alabama,AL,Madison,101 Sivley Rd,Huntsville,35801,6530510.0,Huntsville Hospital,958,NaN,...,0.0,0.0,0.0,NaN,Yes,NaN,(256) 265-1000,"101 Sivley Rd, Huntsville, Alabama 35801",34.720467,-86.580963
7,Alabama,AL,Montgomery,2105 E South Blvd,Montgomery,36116,6530705.0,Baptist Medical Center South,492,NaN,...,1.0,0.0,0.0,NaN,Yes,NaN,(334) 288-2100,"2105 E South Blvd, Montgomery, Alabama 36116",32.327953,-86.277782

### Using `folium.plugins.MarkerCluster` to manage overlapping markers

For a better visualization when many points are close to each other, `MarkerCluster` groups nearby markers into a single icon. As you zoom in, the clusters expand, eventually revealing individual markers. This prevents the map from becoming cluttered.

First, we need to import `MarkerCluster`.

In [85]:
# Initialize a Folium map centered around the average coordinates of the burn centers
# Using a default location if df_burn_center is empty or has no coordinates
if not df_burn_center.empty and 'Latitude' in df_burn_center.columns and 'Longitude' in df_burn_center.columns:
    map_center = [df_burn_center['Latitude'].mean(), df_burn_center['Longitude'].mean()]
else:
    map_center = [39.8283, -98.5795] # Geographic center of the contiguous United States

m_150 = folium.Map(location=map_center, zoom_start=4)
print("Folium map initialized for 150 mile+ range visualization.")

Folium map initialized for 150 mile+ range visualization.

In [86]:
for index, row in df_burn_center.iterrows():
    # Create popup content for burn centers
    popup_content = f"<b>Burn Center:</b> {row['HOSPITAL_NAME']}<br>"
    popup_content += f"<b>Address:</b> {row['FULL_ADDRESS']}<br>"
    popup_content += f"<b>Burn Beds:</b> {row['BURN_BEDS'] if pd.notna(row['BURN_BEDS']) else 'N/A'}<br>"
    popup_content += f"<b>ACS Verified:</b> {row['ACS_VERIFIED']}<br>"
    popup_content += f"<b>ABA Verified:</b> {row['ABA_VERIFIED']}"

    # Add marker for burn center
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=folium.Popup(popup_content, max_width=300),
        tooltip=row['HOSPITAL_NAME'],
        icon=folium.Icon(color='red', icon='fire', prefix='fa') # Distinct icon for burn centers
    ).add_to(m_150)

    # Add a 20-mile radius circle around burn centers (1 mile = 1609.34 meters)
    folium.Circle(
        location=[row['Latitude'], row['Longitude']],
        radius=20 * 1609.34, # Radius in meters
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity=0.1
    ).add_to(m_150)


for index, row in non_burn_centers_150_miles_plus.iterrows():
    # Create popup content for non-burn centers > 150 miles away
    popup_content = f"<b>Non-Burn Center (>150 mi):</b> {row['HOSPITAL_NAME']}<br>"
    popup_content += f"<b>Address:</b> {row['FULL_ADDRESS']}"

    # Add marker for nearby non-burn center with a different color
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=folium.Popup(popup_content, max_width=300),
        tooltip=row['HOSPITAL_NAME'],
        icon=folium.Icon(color='blue', icon='hospital', prefix='fa') # Distinct icon for non-burn centers
    ).add_to(m_150)

# Display the map
m_150

We see that the ideal for transporting people.

* The ideal is 20 miles of driving
* The other ideal is 30-150 for air transportation.
* The rest beyond that is best for tele medicine and consider add a burn center to those areas

Resorces for the distance:
* https://pmc.ncbi.nlm.nih.gov/articles/PMC9905382/#s10

* https://jamanetwork.com/journals/jama/fullarticle/184780

* https://plasticsurgerykey.com/pre-hospital-management-transportation-and-emergency-care/

## Overall Summary of Findings

### Key Findings
*   **Within 20-mile radius:** A total of 222 non-burn centers were identified within a 20-mile radius of at least one burn center. These centers were successfully visualized on an interactive Folium map, with burn centers marked in red (including a 20-mile radius circle) and nearby non-burn centers in blue.
*   **Within 30-150 mile range:** 406 non-burn centers were found to be within a distance of 30 to 150 miles from at least one burn center. This group was also visualized on a separate interactive Folium map with similar marker conventions.
*   **Beyond 150-mile range:** 457 non-burn centers were identified where the closest burn center was more than 150 miles away. These locations were also presented on an interactive Folium map.

### Insights and Next Steps
*   **Immediate Vicinity (<=20 miles):** The significant number of non-burn centers within a 20-mile radius indicates strong potential for efficient patient transfer, collaborative care, and post-acute care coordination. Further analysis could focus on the specific services offered by these facilities to optimize patient pathways.
*   **Intermediate Distance (30-150 miles):** The large number of non-burn centers in this range suggests opportunities for establishing robust referral networks and exploring intermediate care solutions. Investigating the capabilities of these 406 centers could help in assessing their potential for initial stabilization or intermediate burn treatment. These places can have helicopter pick reat patients
*   **Remote Areas (>150 miles):** The 457 non-burn centers located beyond 150 miles highlight critical gaps in access to specialized burn care. These regions are likely to rely heavily on telemedicine for initial consultations and require robust aeromedical transport protocols for physical transfers. A crucial next step would be to evaluate the feasibility and necessity of establishing new burn centers or specialized units in these underserved areas to improve patient outcomes and reduce critical travel times.

## Overall Summary of Findings

In [87]:
import pandas as pd
from pathlib import Path

# Save analysis output to CSV
output_dir = Path("../outputs")
output_dir.mkdir(parents=True, exist_ok=True)

df_nearby_non_burn_centers.to_csv(output_dir / "analysis2_nearby_non_burn_centers.csv", index=False)
df_non_burn_centers_30_150_miles.to_csv(output_dir / "analysis2_non_burn_centers_30_150_miles.csv", index=False)
non_burn_centers_150_miles_plus.to_csv(output_dir / "analysis2_non_burn_centers_150_miles_plus.csv", index=False)

print(f"Analysis output saved to {output_dir}")

Analysis output saved to ..\outputs